import { rosharGazetteer } from '../world/gazetteer/catalog';
import { detailedLocationAnchors } from '../world/cartography/geography';

export const sources = {
  hearthstone:{title:'Hearthstone · architecture',author:'The Coppermind',url:'https://coppermind.net/wiki/Hearthstone?mobileaction=toggle_view_desktop',kind:'Book-cited reference'},
  revolar:{title:'Revolar · geography',author:'The Coppermind',url:'https://coppermind.net/wiki/Revolar',kind:'Book-cited reference'},
  kasitor:{title:'Kasitor · the harbor',author:'The Coppermind',url:'https://coppermind.net/wiki/Kasitor?mobileaction=toggle_view_desktop',kind:'Book-cited reference'},
  rall:{title:'Rall Elorim · published city illustration',author:'Romain Kurdi / Brotherwise Games',url:'https://www.kickstarter.com/projects/brotherwise/the-stormlight-archive-rpg/posts/4168574',kind:'Cosmere RPG illustration'},
  rallText:{title:'Rall Elorim · the City of Shadows',author:'The Coppermind',url:'https://coppermind.net/wiki?mobileaction=toggle_view_desktop&title=Rall_Elorim',kind:'Book-cited reference'},
  highstorm:{title:'Highstorm · stormwall and direction',author:'The Coppermind',url:'https://coppermind.net/wiki/Highstorm',kind:'Book-cited reference'},
  yeddaw:{title:'Yeddaw · trenches and daily life',author:'The Coppermind',url:'https://coppermind.net/wiki/Yeddaw',kind:'Book-cited reference'},
  sesemalex:{title:'Sesemalex Dar · sheltered troughs',author:'Reactor / Stormlight ecology',url:'https://reactormag.com/the-ecology-of-roshar-continued-quest-for-blood/',kind:'Book-based architectural description'},
  listeners:{title:'Listeners · homes, forms and rhythms',author:'The Coppermind',url:'https://coppermind.net/wiki/Listener?mobileaction=toggle_view_desktop',kind:'Book-cited reference'},
  surges:{title:'Surgebinding · the ten Surges',author:'The Coppermind',url:'https://coppermind.net/wiki/Surgebinding?mobileaction=toggle_view_desktop',kind:'Book-cited reference'},
  bridge:{title:'Bridge crews · structure and dimensions',author:'The Coppermind',url:'https://coppermind.net/wiki/Alethkar',kind:'Book-cited reference'},
  hunt:{title:'The Way of Kings · chapter 15',author:'Brandon Sanderson',url:'https://www.brandonsanderson.com/blogs/blog/the-way-of-kings-chapter-15-d',kind:'Author-hosted excerpt'},
  windrunners: {title:'Windrunners • orders and duties',author:'Brandon Sanderson',url:'https://www.brandonsanderson.com/blogs/blog/the-ten-orders-of-knights-radiant',kind:'Author’s reference'},
  radiantProse: {title:'Windrunner uniforms and Stormlight',author:'Brandon Sanderson / Gollancz',url:'https://www.hachette.co.uk/wp-content/uploads/2020/10/Rhythm-of-War-UK-Chapter-sampler.pdf',kind:'Published chapter sampler · pp. 58, 68'},
  towerStrata: {title:'Urithiru • stone and strata',author:'The Coppermind',url:'https://coppermind.net/wiki/Urithiru?mobileaction=toggle_view_desktop',kind:'Book-cited reference'},
  map: { title: 'Roshar • official map', author: 'Isaac Stewart / Dragonsteel', url: 'https://www.dragonsteelbooks.com/products/roshar-map-poster', kind: 'Official cartography' },
  tower: { title: 'Urithiru • Shallan’s sketch', author: 'Ben McSweeney', url: 'https://coppermind.net/wiki/File:Urithiru.jpg', kind: 'In-book illustration' },
  towerText: { title: 'Oathbringer • chapters 4–6', author: 'Brandon Sanderson / Reactor', url: 'https://reactormag.com/oathbringer-by-brandon-sanderson-chapters-4-6/', kind: 'Published prose' },
  kholinar: { title: 'Kholinar and its windblades', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Kholinar', kind: 'Book-cited reference' },
  kholinarMap: { title: 'Map of Kholinar', author: 'Isaac Stewart', url: 'https://coppermind.net/wiki/File:Kholinar.jpg', kind: 'Official cartography' },
  kharbranth: { title: 'Kharbranth • geography & architecture', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Kharbranth', kind: 'Book-cited reference' },
  kharbranthArt: { title: 'Kharbranth • port to Conclave', author: 'Isaac Stewart / Dragonsteel', url: 'https://www.brandonsanderson.com/the-way-of-kings-interior-illustrations-now-uploaded/', kind: 'In-book illustration' },
  thaylen: { title: 'A survey of the Great Thaylen City', author: 'Isaac Stewart', url: 'https://coppermind.net/wiki/File:Thaylen_City.jpg', kind: 'Official cartography' },
  azimir: { title: 'The Bronze Palace', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Bronze_Palace', kind: 'Book-cited reference' },
  azimirMap: { title: 'Plan of the City of Azimir', author: 'Isaac Stewart', url: 'https://coppermind.net/wiki/File:Plan_of_the_City_of_Azimir.jpg', kind: 'Official cartography' },
  plains: { title: 'Shattered Plains • maps & symmetry', author: 'Isaac Stewart / Ben McSweeney', url: 'https://uploads.coppermind.net/Shattered_Plains_WoR_map.jpeg', kind: 'Published density sketch' },
  plainsText: { title: 'Shattered Plains • terrain', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Shattered_Plains', kind: 'Book-cited reference' },
  shinovar: { title: 'Shinovar • geography & ecology', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Shinovar', kind: 'Book-cited reference' },
  purelake: { title: 'Purelake • geography', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Purelake', kind: 'Book-cited reference' },
  vedenar: { title: 'Vedenar', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Vedenar', kind: 'Book-cited reference' },
  akinah: { title: 'Akinah', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Akinah', kind: 'Book-cited reference' },
  chull: { title: 'Chull • anatomy & behavior', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Chull', kind: 'Book-cited reference' },
  axehound: { title: 'Axehound', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Axehound', kind: 'Book-cited reference' },
  skyeel: { title: 'Skyeel • anatomy & flight', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Skyeel', kind: 'Book-cited reference' },
  chasmfiend: { title: 'Chasmfiend • anatomy', author: 'The Coppermind', url: 'https://coppermind.net/wiki/Chasmfiend', kind: 'Book-cited reference' },
  fourCities: { title: 'Four Cities • cymatic plans', author: 'Isaac Stewart', url: 'https://uploads.coppermind.net/Four_Cities.jpg', kind: 'In-book illustration' },
  ecology: { title: 'A world of stone and storms', author: 'Brandon Sanderson', url: 'https://www.brandonsanderson.com/pages/the-stormlight-archive-series', kind: 'Author’s introduction' },
};
export type SourceId = keyof typeof sources;
export type PlaceId = 'hearthstone' | 'revolar' | 'kasitor' | 'rall-elorim' | 'urithiru' | 'kholinar' | 'kharbranth' | 'thaylen-city' | 'azimir' | 'shattered-plains' | 'shinovar' | 'purelake' | 'vedenar' | 'akinah' | 'yeddaw' | 'sesemalex-dar';
export interface Place {
  id: PlaceId; name: string; region: string; subtitle: string; anchor: readonly [number, number];
  description: string; features: string[]; interpretation: string; sources: SourceId[];
  ecology: string; icon: 'tower' | 'city' | 'port' | 'mountain' | 'leaf' | 'water';
}
const mappedAnchor=(id:string)=>rosharGazetteer.find(p=>p.id===id)!.world!;
export const places: Place[] = [
  { id:'urithiru', name:'Urithiru', region:'Central mountains', subtitle:'Above the highstorms', anchor:detailedLocationAnchors.urithiru, icon:'tower', description:'Ten immense terraces rise out of the mountain. A flat eastern face shelters a city whose lower levels disappear into the surrounding peaks.', features:['Ten semicircular tiers, eighteen floors each','Eastern glass wall and mountain-integrated shoulders','Ten separate Oathgate platforms'], interpretation:'The tier proportions follow the published sketch. Rock formations, terrace planting and the local population are reconstructed. Height is approximately 823 m; the books do not provide a surveyed footprint or precise exterior color swatches. Blue-uniformed Windrunner patrols illustrate activity at the tower; their count and routes are interpreted.', sources:['tower','towerText','towerStrata','windrunners','radiantProse','surges','map'], ecology:'Windrunner patrols above the terraces; ordinary highstorms pass below the city.' },
  { id:'kholinar', name:'Kholinar', region:'Alethkar', subtitle:'The city of windblades', anchor:detailedLocationAnchors.kholinar, icon:'city', description:'Layered stone fins shelter the Alethi capital. Streets gather between the windblades beneath a palace raised above the northern city.', features:['Stratified red, cream and orange windblades','An elevated northern palace and Sunwalk','An enclosing wall integrated with natural stone'], interpretation:'The main forms follow the city map. Individual houses, market stalls and the walkable district are representative reconstructions.', sources:['kholinarMap','kholinar','map'], ecology:'Market crowds, patrolling guards, chulls and six-legged axehounds.' },
  { id:'kharbranth', name:'Kharbranth', region:'Frostlands coast', subtitle:'The City of Bells', anchor:detailedLocationAnchors.kharbranth, icon:'port', description:'A brilliant wedge of color climbs from a sheltered harbor toward the Conclave. Porters carry goods up the switchback streets while bells hang above the city.', features:['A mountain-sheltered wedge-shaped port','Color-coded houses and shops along switchbacks','Bells, docks and the upper Conclave'], interpretation:'The port-to-Conclave relationship follows the in-book drawing. Red/orange façades and colored shop accents follow the prose; exact swatches, fine building layouts and harbor traffic are interpreted; the underground Palanaeum is not depicted as a separate exterior tower.', sources:['kharbranthArt','kharbranth','map'], ecology:'Porters and skyeels above the harbor. Steep streets favor people carrying goods over chull carts.' },
  { id:'thaylen-city', name:'Thaylen City', region:'Thaylenah', subtitle:'Where sea roads meet', anchor:detailedLocationAnchors['thaylen-city'], icon:'port', description:'A trading city between steep mountains and the sea, with an ancient patterned center, layered wards and a broad field beyond the western wall.', features:['A patterned Ancient Ward','A western wall, field and working harbor','A Royal Ward rising toward the mountains'], interpretation:'Ward relationships follow the official map. The harbor and street-level architecture show an intact, illustrative city rather than a specific battle aftermath.', sources:['thaylen','map'], ecology:'Dockworkers, merchant caravans and coastal skyeels.' },
  { id:'azimir', name:'Azimir', region:'Azir', subtitle:'The bronze heart of the empire', anchor:detailedLocationAnchors.azir, icon:'city', description:'Broad, orderly boulevards lead toward the Bronze Palace. Its rounded forms, metal-clad trees and domed courts reflect the wealth of the Azish capital.', features:['A symmetrical network of broad boulevards','Bulbous bronze palace buildings and ornamental trees','A separate domed Grand Market on the Oathgate'], interpretation:'The palace and market follow textual descriptions; the modeled street district is an original interpretation of the ordered urban plan.', sources:['azimir','azimirMap','map'], ecology:'Clerks and petitioners share the boulevards with cargo chulls.' },
  { id:'shattered-plains', name:'Shattered Plains', region:'Eastern Roshar', subtitle:'A pattern in broken stone', anchor:detailedLocationAnchors['shattered-plains'], icon:'mountain', description:'Deep chasms divide an immense field of plateaus. Seen from above, the fractures echo a fourfold pattern around the ruins of Stormseat.', features:['Fourfold organization with irregular eroded edges','Deep chasms and a central ruined settlement','Western camps and bridges across selected gaps'], interpretation:'The published sketch maps plateau density, not every individual outline. The model uses a fourfold field of irregular adjoining plateaus with wider eastern gaps. Creature paths stay inside broad chasm corridors and people use selected western crossings.', sources:['plains','plainsText','chasmfiend','bridge','hunt','listeners'], ecology:'Bridge workers, supply chulls and eighteen-limbed chasmfiends below the plateaus.' },
  { id:'shinovar', name:'Shinovar', region:'Western Roshar', subtitle:'A sheltered green world', anchor:detailedLocationAnchors.shinovar, icon:'leaf', description:'Behind the Misted Mountains, soil and ordinary grass cover the ground. Earth-built farmhouses sit among fields and trees whose leaves do not retreat from the wind.', features:['A mountain-sheltered agricultural valley','Earth and clay houses rather than stone construction','Ordinary trees, fields and grazing animals'], interpretation:'This is a representative rural valley. It is not an exact reconstruction of a named monastery or a claim about the unknown Oathgate position.', sources:['shinovar','map'], ecology:'Farmers and grazing livestock. Highstorms weaken into ordinary rain behind the mountains.' },
  { id:'purelake', name:'Purelake', region:'Sela Tales', subtitle:'A horizon of shallow water', anchor:detailedLocationAnchors.purelake, icon:'water', description:'Warm, shallow water stretches across a vast inland basin. Fishers wade over the lakebed between rock outcrops and small waterside dwellings.', features:['A shallow lake with an exposed stone bed','Wading fishers and schools of fish','Rock outcrops and low dwellings'], interpretation:'The settlement is a representative lakeside community. Its paths and buildings are invented to illustrate daily life, not placed as a canonical named city.', sources:['purelake','map'], ecology:'Fish shoals and wading fishers; lake water recedes as a highstorm approaches.' },
  { id:'vedenar', name:'Vedenar', region:'Jah Keved', subtitle:'The Veden capital', anchor:detailedLocationAnchors.vedenar, icon:'city', description:'The Veden capital rises on cliffs above the Tarat Sea. Its ancient core follows a rotational pattern, with gardens on broad plate-like terraces.', features:['A rotationally patterned ancient core','Plate-like terrace gardens above the city','Southern sea cliffs and a river to the west'], interpretation:'The ancient core follows the published city diagram. Individual architecture and terrace dimensions are interpreted. This view depicts an illustrative intact city, not the later civil-war damage.', sources:['fourCities','vedenar','map'], ecology:'Residents, market workers and domestic axehounds.' },
  { id:'akinah', name:'Akinah', region:'Aimia', subtitle:'The island ruins', anchor:detailedLocationAnchors.aimia, icon:'water', description:'An isolated island city survives in fragments: weathered courts, broken columns and overgrown stone beside the sea.', features:['Ten flower-like sections around a central hub','Tall central rocks and a ring of stone spikes','A concealed subterranean Oathgate'], interpretation:'The tenfold plan follows the published Four Cities diagram. Building remains are interpreted, and the buried Oathgate is not invented as a visible active portal. The continental marker identifies the Aimia region rather than a surveyed island position.', sources:['fourCities','akinah','map'], ecology:'Coastal skyeels and small shell-dwelling creatures. No resident human crowd.' },
];
places.push(
  {id:'yeddaw',name:'Yeddaw',region:'Tashikk',subtitle:'A city beneath the fields',anchor:mappedAnchor('yeddaw'),icon:'city',description:'A spiral of sunken streets winds beneath farmland. Houses line the deep cuts; lanterns lead toward the moundlike Grand Indicium at the center.',features:['Spiraling trenches below farmland','Central Grand Indicium above the ground','Drainage slopes away from the center'],interpretation:'The spiral, farms and central mound follow Edgedancer descriptions. The number of cuts, architecture, exact colors and street dimensions are interpreted; the map anchor comes from the registered gazetteer.',sources:['yeddaw','map'],ecology:'Tashikki residents, market porters and Sun Day cake stalls.'},
  {id:'sesemalex-dar',name:'Sesemalex Dar',region:'Emul',subtitle:'Shelter in the stone',anchor:mappedAnchor('sesemalex-dar'),icon:'city',description:'Long troughs protect the Emuli capital below the surrounding stone. Partial lids shelter homes while channels carry stormwater through the sunken streets.',features:['Long troughs cut below ground','Protective lids over selected sections','Drainage along the lowest streets'],interpretation:'The troughs, covers and drainage follow descriptions of the city. No surveyed plan is published in the consulted references; the seven modeled troughs and muted stone palette are illustrative. The map anchor comes from the registered gazetteer.',sources:['sesemalex','map'],ecology:'Merchants and neighbors move along the sheltered streets.'}
);
places.push(
  {id:'hearthstone',name:'Hearthstone',region:'Northern Alethkar',subtitle:'In the lee of the breakwall',anchor:mappedAnchor('hearthstone'),icon:'city',description:'Rows of modest wedge-shaped houses turn their sloping eastern walls toward the storms. A steep breakwall shelters the village, its grain stores and a white manor.',features:['One hundred east-sloping homes','Windows and doors on sheltered western walls','Lavis fields, grain stores and a white manor'],interpretation:'House shape and the breakwall follow textual descriptions. The arrangement of streets, manor grounds and market is reconstructed. The geographic anchor follows the registered map.',sources:['hearthstone','map'],ecology:'Neighbors visit the bakery while chulls haul lavis to the village.'},
  {id:'revolar',name:'Revolar',region:'Alethkar',subtitle:'Beyond the old walls',anchor:mappedAnchor('revolar'),icon:'city',description:'A city fills a hollow between hills and spills up the slopes. Older walls survive inside the growing districts, while caravans gather along the eastern approaches.',features:['Old walls within an expanded city','Irregular hillside districts','Eastern caravan yards and barracks'],interpretation:'The hollow, older walls and eastern yards follow descriptions. Building plans, colors and street geometry are illustrative. No story event or political occupation is depicted.',sources:['revolar','map'],ecology:'Merchants cross the older walls; chull caravans follow the eastern road.'},
  {id:'kasitor',name:'Kasitor',region:'Iri',subtitle:'Four golden pillars in the bay',anchor:mappedAnchor('kasitor'),icon:'port',description:'Warm-colored brick buildings face an Iriali bay. A waterfront platform looks out toward four golden pedestals standing in the water.',features:['Brick buildings beside a warm bay','Four golden pedestals','A public waterfront viewing platform'],interpretation:'Materials, pedestals and the platform follow the prose. The harbor plan, ships, building details and palette are reconstructed; the exact shoreline within the city is not surveyed.',sources:['kasitor','map'],ecology:'Golden-haired Iriali residents gather by the water as cargo chulls work the quay.'},
  {id:'rall-elorim',name:'Rall Elorim',region:'Iri',subtitle:'The City of Shadows',anchor:mappedAnchor('rall-elorim'),icon:'water',description:'A vast overhang holds the city in shadow. Dwellings hang from pendant stone above stepped temples, while waterfalls feed a reservoir lined with pale prayer statues.',features:['A great vaulted overhang and hanging dwellings','Waterfalls, vines and a reservoir temple','Ceramic sphere lamps and prayer statues'],interpretation:'The silhouette and muted stone-and-green palette follow Romain Kurdi’s published Cosmere RPG illustration. Fine architecture and the walkable reservoir district are reconstructed; the exact building plan is illustrative.',sources:['rall','rallText','map'],ecology:'Iriali neighbors share the shaded terraces, lantern walks and reservoir crossings.'}
);
export const placeById = new Map(places.map(p=>[p.id,p]));
