import {useEffect,useState} from 'react';
import {CloudLightning,X,ArrowUpRight,RotateCcw,Sparkles,BookOpen,Play} from 'lucide-react';
import {placeById} from './data';
import {useAtlas,worldClock} from './store';
import {experiences,experienceById,experiencePhase,orders,orderById,discoveries,phaseAt,type OrderId} from './experiences';
export function ExperienceHUD(){
  const s=useAtlas(),[tab,setTab]=useState<'scenes'|'curiosities'>('scenes'),[elapsed,setElapsed]=useState(0);
  useEffect(()=>{const update=()=>setElapsed(worldClock.time-useAtlas.getState().sceneStartedAt);update();const timer=window.setInterval(update,250);return ()=>window.clearInterval(timer);},[s.sceneId,s.sceneStartedAt]);
  const active=s.sceneId?experienceById.get(s.sceneId):undefined,order=orderById.get(s.orderId)!;
  return <>
    {s.scenesOpen&&<aside className="experience-browser surface" aria-label="Living Roshar"><header><div><span className="eyebrow">MOMENTS FROM A LIVING WORLD</span><h2>Beyond the map</h2></div><button className="icon-button" aria-label="Close scenes" onClick={()=>s.set({scenesOpen:false})}><X size={18}/></button></header><div className="experience-tabs"><button aria-pressed={tab==='scenes'} onClick={()=>setTab('scenes')}>Scenes</button><button aria-pressed={tab==='curiosities'} onClick={()=>setTab('curiosities')}>Curiosities <span>{s.discovered.length}/{discoveries.length}</span></button></div>
      {tab==='scenes'?<><button className="storm-scene-entry" onClick={s.followStorm}><CloudLightning size={28}/><span><strong>Ride the highstorm</strong><small>Follow the stormwall across Roshar</small></span><ArrowUpRight size={19}/></button><div className="experience-list">{experiences.map((e,i)=><button className={`experience-card scene-${e.id}`} key={e.id} onClick={()=>s.startScene(e.id)}><span className="scene-number">0{i+1}</span><div><small>{e.eyebrow}</small><strong>{e.name}</strong><p>{e.description}</p></div><Play size={15}/></button>)}</div><p className="experience-note">Illustrative activities with unnamed participants. No story outcomes or character reveals.</p></>:<div className="curiosity-list"><p>Small things reward a closer look. Follow a hint, then inspect the object in the world.</p>{discoveries.map(d=><button key={d.id} onClick={()=>s.seekDiscovery(d.id)}><Sparkles size={18}/><span><strong>{s.discovered.includes(d.id)?d.name:placeById.get(d.place)!.name+' · a curious detail'}</strong><small>{s.discovered.includes(d.id)?d.description:d.hint}</small><em>{s.discovered.includes(d.id)?'Found · revisit':'Follow the hint'}</em></span><ArrowUpRight size={16}/></button>)}<small className="experience-note">Your finds are saved on this device.</small></div>}
    </aside>}
    {active&&!s.scenesOpen&&<section className="active-experience surface" aria-label="Current scene"><header><span className="eyebrow">{s.sceneId==='radiant-arts'?'THE TEN ORDERS':'LIVING ROSHAR'}</span><button className="icon-button" aria-label="Leave scene" onClick={s.endScene}><X size={16}/></button></header><h2>{active.name}</h2>
      {s.sceneId==='radiant-arts'?<><label className="order-picker"><span className="order-jewel" style={{background:order.color,boxShadow:`0 0 13px ${order.color}55`}}/><select aria-label="Radiant order" value={s.orderId} onChange={e=>s.selectOrder(e.target.value as OrderId)}>{orders.map((o,i)=><option key={o.id} value={o.id}>{String(i+1).padStart(2,'0')} · {o.name}</option>)}</select></label><span className="surge-names">{order.surges}</span><p className="scene-caption">{order.action}</p><div className="order-pagination">{orders.map(o=><button key={o.id} style={{background:o.color}} aria-label={`Demonstrate ${o.name}`} aria-pressed={o.id===s.orderId} onClick={()=>s.selectOrder(o.id)}/>)}</div></>:<><div className="phase-line"><span className={s.playing?'live-dot':''}/><strong>{experiencePhase(active.id,elapsed)}</strong><small>{s.playing?'In motion':'Paused'}</small></div><div className="scene-progress" role="progressbar" aria-label="Scene cycle" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(phaseAt(elapsed,active.duration)/active.duration*100)}><i style={{width:`${phaseAt(elapsed,active.duration)/active.duration*100}%`}}/></div><p className="scene-caption">{active.description}</p></>}
      <footer>{s.sceneId==='radiant-arts'&&<button aria-label="Toggle Radiant detail view" onClick={s.sceneDetail}>{s.sceneClose?'Wide view':'Close view'}</button>}<button onClick={()=>s.startScene(active.id)} aria-label="Replay scene"><RotateCcw size={14}/>Replay</button><button onClick={()=>s.set({scenesOpen:true})}><BookOpen size={14}/>More scenes</button></footer>
    </section>}
  </>;
}
