const FieldGuide=lazy(()=>import('./FieldGuide').then(m=>({default:m.FieldGuide})));
import { Suspense, lazy, useEffect, useRef, useState } from 'react';
import { BookOpen, Search, X, Mountain, Landmark, Waves, Leaf, Castle, Anchor, Map, Compass, Plus, Minus, Play, Pause, Sun, CloudLightning, Layers, ChevronRight, ChevronLeft, Menu, ArrowUpRight, HelpCircle, Footprints, RotateCcw, Download, Sparkles } from 'lucide-react';
import { places,placeById,sources,type Place,type PlaceId } from './data';
import {StormHUD} from './StormHUD';
import {ExperienceHUD} from './ExperienceHUD';
import { useAtlas } from './store';
import { rosharGazetteer } from '../world/gazetteer/catalog';
import type { GazetteerPlace } from '../world/gazetteer/types';

const icons={tower:Landmark,city:Castle,port:Anchor,mountain:Mountain,leaf:Leaf,water:Waves};
const aliases:Record<string,PlaceId>={azir:'azimir',aimia:'akinah',narak:'shattered-plains',stormseat:'shattered-plains'};
function PlaceIcon({place}:{place:Place}){const Icon=icons[place.icon];return <Icon aria-hidden="true" size={22} strokeWidth={1.3}/>;}

function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const d=ref.current;d?.showModal();return ()=>d?.close();},[]);
  return <dialog ref={ref} aria-label={title} className="field-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="dialog-inner"><header><h2>{title}</h2><button aria-label={`Close ${title.toLowerCase()}`} className="icon-button" onClick={onClose}><X/></button></header>{children}</div></dialog>;
}
export function HUD(){
  const [guideOpen,setGuideOpen]=useState(()=>new URLSearchParams(window.location.search).get('guide')==='life');
  const s=useAtlas();const place=placeById.get(s.placeId)!;const [query,setQuery]=useState('');const [catalogPlace,setCatalogPlace]=useState<GazetteerPlace|null>(null);const searchRef=useRef<HTMLInputElement>(null);
  const term=query.trim().toLowerCase();
  const own=places.filter(p=>`${p.name} ${p.region}`.toLowerCase().includes(term)||Object.entries(aliases).some(([alias,id])=>id===p.id&&alias.includes(term)));
  const extra=query.trim()?rosharGazetteer.filter(p=>!placeById.has(p.id as PlaceId)&&!aliases[p.id]&&`${p.canonicalName} ${p.nationOrRegion} ${(p.alternateNames??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice(0,35):[];
  const openSearch=()=>{s.set({exploreOpen:true});requestAnimationFrame(()=>searchRef.current?.focus());};
  useEffect(()=>{const key=(e:KeyboardEvent)=>{
    const editing=e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement;
    if((e.key==='k'&&(e.metaKey||e.ctrlKey))||(!editing&&e.key==='/')){e.preventDefault();useAtlas.getState().set({exploreOpen:true});requestAnimationFrame(()=>searchRef.current?.focus());}
    if(!editing&&e.code==='Space'&&!useAtlas.getState().notesOpen&&!useAtlas.getState().helpOpen){e.preventDefault();useAtlas.getState().set({playing:!useAtlas.getState().playing});}
    if(e.key==='Escape'){useAtlas.getState().set({notesOpen:false,settingsOpen:false,helpOpen:false,scenesOpen:false});searchRef.current?.blur();}
  };window.addEventListener('keydown',key);return ()=>window.removeEventListener('keydown',key);},[]);
  const travel=(id:PlaceId)=>{s.travel(id);setCatalogPlace(null);s.set({exploreOpen:false});};
  const pickCatalog=(p:GazetteerPlace)=>{setCatalogPlace(p);s.showAtlas();const point=p.world;if(point){s.set({focusPoint:point});}s.set({exploreOpen:false});};
  const activeSourceIds=s.view==='place'?place.sources:['map','ecology','highstorm'] as const;
  const noteSources=catalogPlace&&s.view==='atlas'?catalogPlace.sources:activeSourceIds.map(id=>sources[id]);
  return <div className={`field-hud ${s.weather==='highstorm'?'is-storm':''} ${s.view==='place'?'is-local':''} ${s.exploreOpen?'explore-is-open':''} ${s.scenesOpen?'scenes-is-open':''} ${s.sceneId?'has-scene':''}`}>
    <header className="field-topbar">
      <button className="brand" onClick={()=>{s.showAtlas();setCatalogPlace(null);}} aria-label="Stormfather home"><Compass size={25}/><span>STORMFATHER</span></button><span className="brand-subtitle">An atlas of Roshar</span>
      <nav className="view-tabs" aria-label="Atlas views"><button aria-current={s.view==='atlas'?'page':undefined} onClick={()=>{s.showAtlas();setCatalogPlace(null);}}><Map size={16}/>Atlas</button><button aria-current={s.view==='place'?'page':undefined} onClick={()=>travel(s.placeId)}><Landmark size={16}/>Place</button></nav>
      <div className="top-actions"><button aria-label="Open field guide" onClick={()=>setGuideOpen(true)}><Footprints size={19}/><span>Life</span></button><button onClick={openSearch} aria-label="Search destinations"><Search size={19}/><span>Search</span></button><button aria-label="Living Roshar scenes" aria-expanded={s.scenesOpen} onClick={()=>s.set({scenesOpen:!s.scenesOpen,exploreOpen:false})}><Sparkles size={19}/><span>Scenes</span></button><button aria-label="Field notes" onClick={()=>s.set({notesOpen:true})}><BookOpen size={20}/><span>Field notes</span></button></div>
    </header>
    <button className="explore-toggle surface" onClick={()=>s.set({exploreOpen:!s.exploreOpen})} aria-expanded={s.exploreOpen} aria-controls="destination-browser">{s.exploreOpen?<ChevronLeft size={18}/>:<Menu size={18}/>}<span>{s.exploreOpen?'Hide destinations':'Explore Roshar'}</span></button>
    {s.exploreOpen&&<aside className="destination-browser surface" id="destination-browser" aria-label="Explore Roshar"><header><h2>Explore Roshar</h2><button className="icon-button" aria-label="Hide destinations" onClick={()=>s.set({exploreOpen:false})}><ChevronLeft size={18}/></button></header><label className="destination-search"><Search size={17}/><input ref={searchRef} aria-label="Search Roshar" placeholder="Find a place…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={15}/></button>}</label><div className="destination-list">{own.map(p=><button key={p.id} aria-label={`${p.name} ${p.region}`} className={`destination ${s.view==='place'&&s.placeId===p.id?'selected':''}`} onClick={()=>travel(p.id)}><PlaceIcon place={p}/><span><strong>{p.name}</strong><small>{p.region}</small></span><ChevronRight size={14}/></button>)}{extra.length>0&&<p className="list-label">From the gazetteer</p>}{extra.map(p=><button className="destination catalog-result" key={p.id} onClick={()=>pickCatalog(p)}><Map size={19}/><span><strong>{p.canonicalName}</strong><small>{p.certainty==='unknown'?'Location not established':p.nationOrRegion??p.kind}</small></span></button>)}{own.length===0&&extra.length===0&&<p className="no-results">No places match “{query}”. Try a city or region.</p>}</div><footer><span className="live-dot"/>{places.length} detailed places<span>·</span><span>Mapped Roshar</span></footer></aside>}
    {s.view==='atlas'&&!catalogPlace&&<section className="atlas-intro surface"><Compass size={39} strokeWidth={.8}/><div><h1>A world shaped<br/> by storms</h1><p>Zoom from the continent into its cities. Follow the streets, wildlife and Radiants of Roshar.</p></div></section>}
    {(s.view==='place'||catalogPlace)&&<aside key={s.view==='place'?s.placeId:catalogPlace?.id} className="place-inspector surface" aria-label="Place details"><div className="place-heading"><span>{s.view==='place'?place.region:catalogPlace?.nationOrRegion}</span><h1>{s.view==='place'?place.name:catalogPlace?.canonicalName}</h1><p>{s.view==='place'?place.subtitle:catalogPlace?.kind}</p></div><p className="place-description">{s.view==='place'?place.description:catalogPlace?.placementReference&&catalogPlace.parentLocationId?'This feature is documented on a local city plan. The continental marker identifies its containing city.':catalogPlace?.certainty==='unknown'?'The references do not establish a reliable map position for this place.':`Shown at its ${catalogPlace?.certainty==='regional'?'approximate regional':'mapped'} position. This place has a gazetteer entry rather than a detailed city reconstruction.`}</p>{s.view==='place'&&<><div className={`place-camera-tabs has-wildlife`} aria-label="Place camera"><button aria-pressed={!s.closeView&&!['wildlife','radiants','scene','discovery'].includes(s.cameraCommand.type)} onClick={()=>s.setClose(false)}><Mountain size={16}/>Overview</button><button aria-pressed={s.closeView} onClick={()=>s.setClose(true)}><Footprints size={16}/>Street view</button>{place.id==='urithiru'?<button aria-pressed={s.cameraCommand.type==='radiants'} onClick={()=>s.command('radiants')}>Radiants</button>:<button aria-pressed={s.cameraCommand.type==='wildlife'} onClick={()=>s.command('wildlife')}>Wildlife</button>}</div><p className="habitat"><Leaf size={16}/>{place.ecology}</p></>}<button className="text-button" onClick={()=>s.set({notesOpen:true})}><BookOpen size={16}/>Sources & reconstruction<ArrowUpRight size={15}/></button></aside>}
    {guideOpen&&<Suspense fallback={null}><FieldGuide onClose={()=>setGuideOpen(false)}/></Suspense>}<ExperienceHUD/><StormHUD/><div className="camera-tools surface" role="group" aria-label="Camera controls"><button aria-label="Zoom in" onClick={()=>s.command('in')}><Plus/></button><button aria-label="Zoom out" onClick={()=>s.command('out')}><Minus/></button><button aria-label="North-up map" onClick={()=>s.command('north')}><Compass/></button><button aria-label="Reset view" onClick={()=>s.command('home')}><RotateCcw size={18}/></button></div>
    <div className="simulation-dock surface" aria-label="Simulation controls"><button className="play-button" aria-label={s.playing?'Pause simulation':'Play simulation'} aria-pressed={!s.playing} onClick={()=>s.set({playing:!s.playing})}>{s.playing?<Pause size={19}/>:<Play size={19}/>}</button><span className="simulation-label">{s.playing?'Living world':'World paused'}</span><label className="speed-control"><span className="sr-only">Simulation speed</span><select aria-label="Simulation speed" value={s.speed} onChange={e=>s.set({speed:Number(e.target.value)})}><option value={.5}>½×</option><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select></label><div className="daylight-control"><Sun size={19}/><label htmlFor="daylight">{s.daylight<.3?'Night':s.daylight<.6?'Dusk':'Daylight'}</label><input id="daylight" aria-label="Daylight" type="range" min="0" max="1" step=".01" value={s.daylight} onChange={e=>s.set({daylight:Number(e.target.value)})}/></div><button className={`storm-button ${s.weather==='highstorm'?'active':''}`} aria-pressed={s.weather==='highstorm'} onClick={()=>s.set({weather:s.weather==='highstorm'?'clear':'highstorm'})}><CloudLightning size={19}/><span>Highstorm</span></button><button className="icon-button layer-button" aria-label="Map and simulation layers" aria-expanded={s.settingsOpen} onClick={()=>s.set({settingsOpen:!s.settingsOpen})}><Layers size={21}/></button></div>
    {s.settingsOpen&&<section className="layer-popover surface" aria-label="Map and simulation layers"><header><h2>Layers</h2><button className="icon-button" aria-label="Close layers" onClick={()=>s.set({settingsOpen:false})}><X size={16}/></button></header>{([['labels','Place labels'],['borders','Political borders'],['people','People'],['creatures','Creatures'],['radiants','Radiants']] as const).map(([key,label])=><label key={key}>{label}<input type="checkbox" checked={s[key]} onChange={e=>s.set({[key]:e.target.checked})}/></label>)}<p>Borders are cartographic estimates. People, creatures and Radiants become visible as you approach a city.</p></section>}
    {s.selectedActor&&<div className="actor-readout surface"><Footprints size={17}/><span>{s.selectedActor}</span><button className="icon-button" aria-label="Dismiss actor details" onClick={()=>s.set({selectedActor:null})}><X size={15}/></button></div>}
    <div className="field-bottomline"><span>{s.view==='atlas'?'Continental atlas · relief exaggerated':'Integrated city · scale enlarged'}</span><span className="interaction-hint">Drag to orbit · scroll to zoom</span><button aria-label="Help and controls" onClick={()=>s.set({helpOpen:true})}><HelpCircle size={17}/></button></div>
    {s.notesOpen&&<Modal title="Field notes" onClose={()=>s.set({notesOpen:false})}><div className="notes-context"><span>{s.view==='place'?place.region:'Roshar'}</span><h3>{s.view==='place'?place.name:catalogPlace?.canonicalName??'Reading this atlas'}</h3><p>{s.view==='place'?place.interpretation:catalogPlace?`Gazetteer placement: ${catalogPlace.certainty}. ${catalogPlace.certainty==='unknown'?'No map pin is shown because a reliable location is not established.':'This is a reference entry; no detailed model is supplied.'}`:'The coastline and place anchors use registered reference cartography. Mountain elevations are an interpretation of mapped ridges, with vertical relief exaggerated for legibility. Cities sit at their registered anchors in the same world. Their footprints are enlarged for exploration; local terrain blends into the continental relief. Exact regional coastlines and fine architecture remain interpretive at this magnification.'}</p></div>{s.view==='place'&&<><h4>What the references establish</h4><ul className="reference-features">{place.features.map(f=><li key={f}>{f}</li>)}</ul></>}<h4>Living world</h4><p className="notes-small">The ten-order court, Parshendi village and unnamed hunting and bridge crews are illustrative activities, not a reconstruction of one book chapter or era. Costume accents follow the author’s order placards; exact swatches and visual power effects are interpreted. Stormlight remains pale. The hunt ends with withdrawal, without a named character outcome. The highstorm moves east to west and weakens toward the western mountains; its displayed height and crossing time are illustrative.</p><h4>Visual assets</h4><p className="notes-small">Facial anatomy adapts the <a href="https://github.com/mrdoob/three.js/tree/dev/examples/models/gltf/LeePerrySmith" target="_blank" rel="noreferrer">Infinite head scan by Lee Perry-Smith</a> under <a href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noreferrer">CC BY 3.0</a>, cropped and recolored for these models. Stone and paving maps are by Rob Tuytel / <a href="https://polyhaven.com" target="_blank" rel="noreferrer">Poly Haven</a> (CC0). Bodies, clothing and creatures are original geometry.</p><h4>References</h4><div className="source-list">{noteSources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer"><BookOpen size={20}/><span><strong>{source.title}</strong><small>{'author' in source&&'kind' in source?`${source.author} · ${source.kind}`:'Gazetteer reference'}</small></span><ArrowUpRight size={17}/></a>)}</div><p className="notes-small">Original fan-made geometry. Stormlight Archive and Roshar belong to Brandon Sanderson and Dragonsteel. This is an unofficial, non-commercial interpretation. Source pages may contain book spoilers.</p>{s.view==='place'&&<a className="download-model" href={`${import.meta.env.BASE_URL}models/v2/${place.id}.glb`} download><Download size={17}/>Download this 3D model</a>}</Modal>}
    {s.helpOpen&&<Modal title="Explore the atlas" onClose={()=>s.set({helpOpen:false})}><div className="help-copy"><p>Scroll toward a city to reveal it on the map, or select a destination to fly there. Zoom out to return to the continent without leaving the scene. Use <strong>Overview</strong> to study the architecture and <strong>Street view</strong> to watch daily life. <strong>Scenes</strong> opens bridge runs, greatshell hunts, a listener village and all ten Radiant power demonstrations. Curiosities contain hints for objects you can discover in the world. <strong>Radiants</strong> at Urithiru follows a Windrunner patrol. <strong>Wildlife</strong> follows a native creature; dragging the camera releases the follow.</p><dl><dt>Orbit</dt><dd>Drag with one finger or the left mouse button</dd><dt>Pan</dt><dd>Two fingers or right mouse drag</dd><dt>Zoom</dt><dd>Pinch, scroll or use + / −</dd><dt>Pause</dt><dd>Space or the playback button</dd><dt>Find a place</dt><dd>/ or ⌘ / Ctrl K</dd><dt>North-up</dt><dd>The compass aligns the camera for map comparison</dd></dl><p>Highstorm changes the simulation. People seek shelter, chulls retract, and local conditions reflect the place’s exposure. Pause freezes the entire living world.</p></div></Modal>}
  </div>;
}
