import type { EasterEgg, WorldLocation } from "./types";

const locationData = [
  {
    id: "roshar",
    name: "Roshar",
    subtitle: "The storm-shaped continent",
    kind: "continent",
    coordinates: { x: 0, z: 0 },
    camera: { position: [0, 72, 69], target: [0, 0, 1] },
    arrivalDetail: "continent",
    regionColor: "#59654d",
    accentColor: "#caaa6b",
    description:
      "A continent of stone, shallow seas, mountain shelters and living ecologies shaped by storms.",
    facts: [
      "Southern hemisphere",
      "Highstorms travel east to west",
      "Flora and cities shelter from the wind",
    ],
    culture: "alethi",
    population: 8_400_000,
    activity: "Continental trade",
  },
  {
    id: "alethkar",
    name: "Alethkar",
    subtitle: "The eastern highkingdom",
    kind: "nation",
    coordinates: { x: 26, z: -1 },
    camera: { position: [36, 25, 23], target: [26, 0, -1] },
    arrivalDetail: "region",
    regionColor: "#6b6345",
    accentColor: "#d7aa4f",
    description:
      "A vast eastern nation of fortified lait cities, windward walls and caravan roads.",
    facts: ["Capital: Kholinar", "Vorin kingdoms", "Storm-facing fortifications"],
    culture: "alethi",
    modelRoot: "Landmark_Kholinar",
    population: 2_120_000,
    activity: "Caravans on the kingways",
  },
  {
    id: "azir",
    name: "Azir",
    subtitle: "Heart of the Makabaki kingdoms",
    kind: "nation",
    coordinates: { x: -11, z: 7 },
    camera: { position: [-2, 20, 27], target: [-11, 0, 7] },
    arrivalDetail: "city",
    regionColor: "#8d6335",
    accentColor: "#e0b05c",
    description:
      "An orderly realm of civic courts, public records, domed halls and exacting administration.",
    facts: ["Capital: Azimir", "Imperial bureaucracy", "Domed civic architecture"],
    culture: "azish",
    modelRoot: "Landmark_Azimir",
    population: 810_000,
    activity: "Petitions and markets",
  },
  {
    id: "shattered-plains",
    name: "Shattered Plains",
    subtitle: "Cymatic chasms of Natanatan",
    kind: "landmark",
    coordinates: { x: 39, z: 8 },
    camera: { position: [49, 14, 24], target: [39, 0.8, 8] },
    arrivalDetail: "city",
    regionColor: "#504a3e",
    accentColor: "#6ee6f2",
    description:
      "Four-fold patterns of plateaus and flooded chasms radiate around the ruins of Stormseat.",
    facts: ["Central ruins: Stormseat", "Warcamps to the west", "Chasms deepen eastward"],
    culture: "singer",
    modelRoot: "Landmark_Shattered_Plains",
    population: 7_350,
    activity: "Bridges, scouts and chasm patrols",
  },
  {
    id: "urithiru",
    name: "Urithiru",
    subtitle: "The tower above the storms",
    kind: "city",
    coordinates: { x: -2, z: 4 },
    camera: { position: [8, 16, 18], target: [-2, 3.1, 4] },
    arrivalDetail: "city",
    regionColor: "#575a59",
    accentColor: "#7ee7ed",
    description:
      "A terraced tower-city built into the mountains, linked to the ancient capitals by Oathgates.",
    facts: ["Layered stone strata", "Ten Oathgate platforms", "Sheltered above the storms"],
    culture: "alethi",
    modelRoot: "Landmark_Urithiru",
    population: 42_000,
    activity: "Oathgate arrivals",
  },
  {
    id: "shinovar",
    name: "Shinovar",
    subtitle: "The sheltered western valleys",
    kind: "nation",
    coordinates: { x: -35, z: 2 },
    camera: { position: [-25, 17, 21], target: [-35, 0, 2] },
    arrivalDetail: "city",
    regionColor: "#3f6c32",
    accentColor: "#9ecb69",
    description:
      "Mountains shelter soft soil, grass, farms and upright trees unfamiliar to eastern Roshar.",
    facts: ["Soil and conventional grass", "Earthen buildings", "Highstorms arrive weakened"],
    culture: "shin",
    modelRoot: "Landmark_Shinovar",
    population: 340_000,
    activity: "Farms and village roads",
  },
  {
    id: "jah-keved",
    name: "Jah Keved",
    subtitle: "Valleys beneath the Horneater Peaks",
    kind: "nation",
    coordinates: { x: 10, z: -1 },
    camera: { position: [19, 22, 20], target: [10, 0, -1] },
    arrivalDetail: "region",
    regionColor: "#756b43",
    accentColor: "#d39c62",
    description:
      "A broad Veden kingdom of river valleys, estates and mountain passes west of Alethkar.",
    facts: ["Capital: Vedenar", "Horneater Peaks", "River estates and vineyards"],
    culture: "veden",
    population: 1_350_000,
    activity: "River trade",
  },
  {
    id: "purelake",
    name: "Purelake",
    subtitle: "The warm inland shallows",
    kind: "lake",
    coordinates: { x: -12, z: -9 },
    camera: { position: [-3, 13, 5], target: [-12, 0, -9] },
    arrivalDetail: "city",
    regionColor: "#2f777b",
    accentColor: "#72dadd",
    description:
      "Warm crystal-clear water, usually only calf-deep, surrounds rafts and rockbud-like villages.",
    facts: ["Water drains before storms", "Domed homes on low stilts", "Spren-bonded fish"],
    culture: "purelaker",
    modelRoot: "Landmark_Purelake",
    population: 28_000,
    activity: "Fishing rafts on the shallows",
  },
  {
    id: "aimia",
    name: "Aimia",
    subtitle: "The scoured western isles",
    kind: "island",
    coordinates: { x: -48, z: 12 },
    camera: { position: [-39, 16, 26], target: [-48, 0, 12] },
    arrivalDetail: "city",
    regionColor: "#3f4f55",
    accentColor: "#8bd3dc",
    description:
      "Cold, barren islands and storm-wrapped ruins lie beyond the Aimian Sea.",
    facts: ["Akinah's undersea caverns", "Soulcast defensive spikes", "Ruins after the Scouring"],
    culture: "aimian",
    modelRoot: "Landmark_Akinah",
    population: 18,
    activity: "A watchful silence",
  },
  {
    id: "kharbranth",
    name: "Kharbranth",
    subtitle: "The City of Bells",
    kind: "city",
    coordinates: { x: 23, z: 17 },
    camera: { position: [31, 11, 28], target: [23, 2, 17] },
    arrivalDetail: "street",
    regionColor: "#426268",
    accentColor: "#dcb66d",
    description:
      "Color-coded buildings climb the Ralinsa's switchbacks from a sheltered natural harbor.",
    facts: ["The Palanaeum", "Bells throughout the city", "Renowned hospitals"],
    culture: "alethi",
    modelRoot: "Landmark_Kharbranth",
    population: 125_000,
    activity: "Crowded docks and night markets",
  },
  {
    id: "kholinar",
    name: "Kholinar",
    subtitle: "The city of windblades",
    kind: "city",
    coordinates: { x: 29, z: -2 },
    camera: { position: [37, 13, 12], target: [29, 1, -2] },
    arrivalDetail: "street",
    regionColor: "#65533b",
    accentColor: "#d7aa4f",
    description:
      "Alethkar's capital gathers behind massive eastern windbreaks and a fortified palace.",
    facts: ["The Sunwalk", "Concentric defenses", "Kholin palace complex"],
    culture: "alethi",
    modelRoot: "Landmark_Kholinar",
    population: 280_000,
    activity: "Markets beneath the windblades",
  },
  {
    id: "thaylen-city",
    name: "Thaylen City",
    subtitle: "Harbor of merchants",
    kind: "city",
    coordinates: { x: 19, z: 23 },
    camera: { position: [28, 16, 35], target: [19, 0, 23] },
    arrivalDetail: "city",
    regionColor: "#4f615c",
    accentColor: "#bcaa84",
    description:
      "A southern mercantile port built around sheltered water and far-reaching trade.",
    facts: ["Thaylenah", "Ocean trade", "Merchant fleets"],
    culture: "thaylen",
    population: 95_000,
    activity: "Ships entering harbor",
  },
] as const satisfies readonly WorldLocation[];

export type LocationId = (typeof locationData)[number]["id"];

export const locations: readonly WorldLocation[] = locationData;

export const travelLocations = locations.slice(0, 10);
export const secondaryLocations = locations.slice(10);

export const locationById = new Map<string, WorldLocation>(
  locations.map((location) => [location.id, location]),
);

export const easterEggs: readonly EasterEgg[] = [
  {
    id: "wandersail",
    coordinates: { x: -11, z: -18 },
    height: 0.5,
    title: "A peculiar ship",
    message: "A weathered sail points toward islands that may not be islands at all.",
  },
  {
    id: "flute",
    coordinates: { x: 30, z: -3 },
    height: 1.4,
    title: "A forgotten flute",
    message: "Someone very old is going to be annoyed about this.",
  },
  {
    id: "stick",
    coordinates: { x: 9, z: -2 },
    height: 0.8,
    title: "A remarkably stubborn stick",
    message: "It remains, emphatically, a stick.",
  },
  {
    id: "chicken",
    coordinates: { x: 21, z: 22 },
    height: 0.9,
    title: "An unusual chicken",
    message: "Locals insist every bird is a chicken. This one looks unconvinced.",
  },
  {
    id: "bridge-four",
    coordinates: { x: 38.5, z: 8.8 },
    height: 0.7,
    title: "Four scratched glyphs",
    message: "The mark is small, but the chasm wind seems to salute it.",
  },
  {
    id: "cremling",
    coordinates: { x: -46, z: 12 },
    height: 0.65,
    title: "One cremling too many",
    message: "For a heartbeat, the swarm appears to look back.",
  },
  {
    id: "black-sand",
    coordinates: { x: -13, z: 7.8 },
    height: 0.65,
    title: "Black sand in a brass vial",
    message: "The grains lean toward something you cannot see.",
  },
  {
    id: "pancake",
    coordinates: { x: -11.2, z: -8.6 },
    height: 0.7,
    title: "A suspiciously perfect pancake",
    message: "Lift would approve. Probably.",
  },
  {
    id: "sword-nimi",
    coordinates: { x: -33.8, z: 1.2 },
    height: 0.75,
    title: "A talkative-looking scabbard",
    message: "The safest choice is to keep walking.",
  },
  {
    id: "worldhopper",
    coordinates: { x: 4.5, z: 4.2 },
    height: 2.1,
    title: "The wrong kind of coin",
    message: "Its face belongs to no Rosharan ruler.",
  },
];
