import type { DetailLevel } from "../types";
import { cityPlanGazetteer } from "./cityPlans";
import { literaryPlaceGazetteer } from "./literaryPlaces";
import {
  referencePixelToGazetteerWorld,
  sourceMapPixelToReferencePixel,
} from "./transform";
import { shinovarGazetteer } from "./shinovar";
import type {
  GazetteerCategory,
  GazetteerCertainty,
  GazetteerKind,
  GazetteerPlace,
  GazetteerSource,
  VisualizationArchetype,
} from "./types";
import { defaultGazetteerCategory } from "./types";

export const ROSHAR_MAP_SOURCE_COMMIT =
  "dfbf1c167808f29176a7c01469e8ba957a8b3692";

const ROSHAR_MAP_LOCATIONS_URL =
  `https://github.com/17thshard/roshar-map/blob/${ROSHAR_MAP_SOURCE_COMMIT}/src/stores/locations.json`;
const ROSHAR_MAP_LANGUAGE_URL =
  `https://github.com/17thshard/roshar-map/blob/${ROSHAR_MAP_SOURCE_COMMIT}/src/lang/en-US.lang.json`;

const mapCoordinateSource: GazetteerSource = {
  title: `17th Shard Interactive Map — locations.json (${ROSHAR_MAP_SOURCE_COMMIT.slice(0, 7)})`,
  url: ROSHAR_MAP_LOCATIONS_URL,
};

const mapLanguageSource: GazetteerSource = {
  title: `17th Shard Interactive Map — English locale (${ROSHAR_MAP_SOURCE_COMMIT.slice(0, 7)})`,
  url: ROSHAR_MAP_LANGUAGE_URL,
};

function coppermindSource(slug: string, title: string): GazetteerSource {
  return {
    title: `The Coppermind — ${title}`,
    url: `https://coppermind.net/wiki/${slug}`,
  };
}

function mapSources(
  coppermindSlug: string,
  canonicalName: string,
): readonly GazetteerSource[] {
  return [
    mapCoordinateSource,
    mapLanguageSource,
    coppermindSource(coppermindSlug, canonicalName),
  ];
}

interface LocatedPlaceInput {
  id: string;
  canonicalName: string;
  kind: GazetteerKind;
  category?: GazetteerCategory;
  nationOrRegion: string;
  minimumLod: DetailLevel;
  visualization: VisualizationArchetype;
  sourceMapPixel?: readonly [number, number];
  referencePixel?: readonly [number, number];
  certainty?: Exclude<GazetteerCertainty, "unknown">;
  coppermindSlug: string;
  alternateNames?: readonly string[];
  sources?: readonly GazetteerSource[];
}

function located(input: LocatedPlaceInput): GazetteerPlace {
  const referencePixel =
    input.referencePixel ??
    (input.sourceMapPixel
      ? sourceMapPixelToReferencePixel(input.sourceMapPixel)
      : null);
  if (referencePixel === null) {
    throw new Error(`Located gazetteer place ${input.id} needs coordinates`);
  }
  return {
    id: input.id,
    canonicalName: input.canonicalName,
    kind: input.kind,
    category: input.category ?? defaultGazetteerCategory(input.kind),
    nationOrRegion: input.nationOrRegion,
    certainty: input.certainty ?? "precise",
    minimumLod: input.minimumLod,
    visualization: input.visualization,
    sourceMapPixel: input.sourceMapPixel ?? null,
    referencePixel,
    world: referencePixelToGazetteerWorld(referencePixel),
    renderable: true,
    alternateNames: input.alternateNames,
    sources:
      input.sources ??
      mapSources(input.coppermindSlug, input.canonicalName),
  };
}

function unknown(
  input: Omit<
    LocatedPlaceInput,
    "sourceMapPixel" | "referencePixel" | "certainty"
  >,
): GazetteerPlace {
  return {
    id: input.id,
    canonicalName: input.canonicalName,
    kind: input.kind,
    category: input.category ?? defaultGazetteerCategory(input.kind),
    nationOrRegion: input.nationOrRegion,
    certainty: "unknown",
    minimumLod: input.minimumLod,
    visualization: input.visualization,
    sourceMapPixel: null,
    referencePixel: null,
    world: null,
    renderable: false,
    alternateNames: input.alternateNames,
    sources:
      input.sources ??
      [coppermindSource(input.coppermindSlug, input.canonicalName)],
  };
}

/**
 * Principal points copied from the same supplied 1889 × 1144 reference used by
 * geography.ts. These deliberately override the projective registration so the
 * gazetteer and the existing travel destinations share one authoritative point.
 */
const destinationReferencePixels = {
  alethkar: [1480, 600],
  "jah-keved": [1170, 535],
  herdaz: [1360, 360],
  kharbranth: [1105, 885],
  thaylenah: [1150, 1000],
  azir: [620, 680],
  shinovar: [335, 560],
  aimia: [95, 685],
  iri: [505, 350],
  urithiru: [830, 700],
  "shattered-plains": [1575, 815],
  tashikk: [620, 805],
  emul: [750, 760],
  tukar: [650, 900],
  purelake: [800, 540],
  kholinar: [1405, 540],
  "thaylen-city": [1090, 970],
  "tu-bayla": [1010, 555],
  frostlands: [1410, 885],
} as const satisfies Record<string, readonly [number, number]>;

/**
 * Physical-Realm Roshar gazetteer.
 *
 * The first 83 entries preserve every distinct non-Shadesmar location from the
 * cited 17th Shard map. The remaining entries add important named exteriors,
 * institutions, rivers, and explicitly unplaceable locations from the novels.
 */
export const rosharGazetteer: readonly GazetteerPlace[] = [
  located({
    id: "alethkar",
    canonicalName: "Alethkar",
    kind: "nation",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [718.9, 277.2],
    referencePixel: destinationReferencePixels.alethkar,
    certainty: "regional",
    coppermindSlug: "Alethkar",
  }),
  located({
    id: "jah-keved",
    canonicalName: "Jah Keved",
    kind: "nation",
    nationOrRegion: "Jah Keved",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [621.1, 245.3],
    referencePixel: destinationReferencePixels["jah-keved"],
    certainty: "regional",
    coppermindSlug: "Jah_Keved",
  }),
  located({
    id: "herdaz",
    canonicalName: "Herdaz",
    kind: "nation",
    nationOrRegion: "Herdaz",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [690.6, 183.5],
    referencePixel: destinationReferencePixels.herdaz,
    certainty: "regional",
    coppermindSlug: "Herdaz",
  }),
  located({
    id: "kharbranth",
    canonicalName: "Kharbranth",
    kind: "city",
    category: "city-state",
    nationOrRegion: "Kharbranth",
    minimumLod: "region",
    visualization: "terrace-city",
    sourceMapPixel: [577.9, 375.1],
    referencePixel: destinationReferencePixels.kharbranth,
    coppermindSlug: "Kharbranth",
  }),
  located({
    id: "thaylenah",
    canonicalName: "Thaylenah",
    kind: "nation",
    nationOrRegion: "Thaylenah",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [615, 427.6],
    referencePixel: destinationReferencePixels.thaylenah,
    certainty: "regional",
    coppermindSlug: "Thaylenah",
  }),
  located({
    id: "azir",
    canonicalName: "Azir",
    kind: "nation",
    nationOrRegion: "Azir",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [414.8, 303.2],
    referencePixel: destinationReferencePixels.azir,
    certainty: "regional",
    coppermindSlug: "Azir",
  }),
  located({
    id: "shinovar",
    canonicalName: "Shinovar",
    kind: "nation",
    nationOrRegion: "Shinovar",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [293.2, 262.4],
    referencePixel: destinationReferencePixels.shinovar,
    certainty: "regional",
    coppermindSlug: "Shinovar",
  }),
  located({
    id: "aimia",
    canonicalName: "Aimia",
    kind: "island",
    category: "region",
    nationOrRegion: "Aimia",
    minimumLod: "continent",
    visualization: "island",
    sourceMapPixel: [187.2, 312.5],
    referencePixel: destinationReferencePixels.aimia,
    certainty: "regional",
    coppermindSlug: "Aimia",
  }),
  located({
    id: "iri",
    canonicalName: "Iri",
    kind: "nation",
    nationOrRegion: "Iri",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [342.4, 171.9],
    referencePixel: destinationReferencePixels.iri,
    certainty: "regional",
    coppermindSlug: "Iri",
  }),
  located({
    id: "rira",
    canonicalName: "Rira",
    kind: "nation",
    nationOrRegion: "Rira",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [401.3, 165.4],
    certainty: "regional",
    coppermindSlug: "Rira_(country)",
  }),
  located({
    id: "reshi-isles",
    canonicalName: "Reshi Isles",
    kind: "island-chain",
    category: "region",
    nationOrRegion: "Reshi Isles",
    minimumLod: "continent",
    visualization: "island-chain",
    sourceMapPixel: [510.4, 120.8],
    certainty: "regional",
    coppermindSlug: "Reshi_Isles",
  }),
  located({
    id: "urithiru",
    canonicalName: "Urithiru",
    kind: "city",
    category: "legendary city",
    nationOrRegion: "Central Roshar",
    minimumLod: "region",
    visualization: "mountain-city",
    sourceMapPixel: [485.7, 318],
    referencePixel: destinationReferencePixels.urithiru,
    coppermindSlug: "Urithiru",
  }),
  located({
    id: "shattered-plains",
    canonicalName: "Shattered Plains",
    kind: "plains",
    category: "region",
    nationOrRegion: "Former Natanatan",
    minimumLod: "continent",
    visualization: "shattered-plains",
    sourceMapPixel: [768, 364.6],
    referencePixel: destinationReferencePixels["shattered-plains"],
    certainty: "regional",
    coppermindSlug: "Shattered_Plains",
  }),
  located({
    id: "tashikk",
    canonicalName: "Tashikk",
    kind: "nation",
    nationOrRegion: "Tashikk",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [378, 344.7],
    referencePixel: destinationReferencePixels.tashikk,
    certainty: "regional",
    coppermindSlug: "Tashikk",
  }),
  located({
    id: "emul",
    canonicalName: "Emul",
    kind: "nation",
    nationOrRegion: "Emul",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [439.3, 342.4],
    referencePixel: destinationReferencePixels.emul,
    certainty: "regional",
    coppermindSlug: "Emul",
  }),
  located({
    id: "tukar",
    canonicalName: "Tukar",
    kind: "nation",
    nationOrRegion: "Tukar",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [411.4, 381.6],
    referencePixel: destinationReferencePixels.tukar,
    certainty: "regional",
    coppermindSlug: "Tukar",
  }),
  located({
    id: "marat",
    canonicalName: "Marat",
    kind: "nation",
    nationOrRegion: "Marat",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [479.3, 373.3],
    certainty: "regional",
    coppermindSlug: "Marat",
  }),
  located({
    id: "liafor",
    canonicalName: "Liafor",
    kind: "nation",
    nationOrRegion: "Liafor",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [337.1, 342.6],
    certainty: "regional",
    coppermindSlug: "Liafor",
  }),
  located({
    id: "babatharnam",
    canonicalName: "Babatharnam",
    kind: "nation",
    nationOrRegion: "Babatharnam",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [386.6, 233.3],
    certainty: "regional",
    coppermindSlug: "Babatharnam",
  }),
  located({
    id: "marabethia",
    canonicalName: "Marabethia",
    kind: "nation",
    nationOrRegion: "Marabethia",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [474.8, 226.5],
    certainty: "regional",
    coppermindSlug: "Marabethia",
  }),
  located({
    id: "purelake",
    canonicalName: "Purelake",
    kind: "lake",
    category: "region",
    nationOrRegion: "Purelake",
    minimumLod: "continent",
    visualization: "shallow-lake",
    sourceMapPixel: [463.1, 251],
    referencePixel: destinationReferencePixels.purelake,
    certainty: "regional",
    coppermindSlug: "Purelake",
  }),
  located({
    id: "kholinar",
    canonicalName: "Kholinar",
    kind: "city",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [738.7, 250.3],
    referencePixel: destinationReferencePixels.kholinar,
    coppermindSlug: "Kholinar",
  }),
  located({
    id: "rathalas",
    canonicalName: "Rathalas",
    kind: "ruin",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "ruined-city",
    sourceMapPixel: [726.9, 304.8],
    coppermindSlug: "Rathalas",
    alternateNames: ["The Rift"],
  }),
  located({
    id: "new-natanan",
    canonicalName: "New Natanan",
    kind: "city",
    category: "kingdom/region",
    nationOrRegion: "New Natanan",
    minimumLod: "region",
    visualization: "port-city",
    sourceMapPixel: [832.1, 371.7],
    coppermindSlug: "New_Natanan",
  }),
  located({
    id: "thaylen-city",
    canonicalName: "Thaylen City",
    kind: "city",
    nationOrRegion: "Thaylenah",
    minimumLod: "region",
    visualization: "port-city",
    sourceMapPixel: [596.9, 419.2],
    referencePixel: destinationReferencePixels["thaylen-city"],
    coppermindSlug: "Thaylen_City",
  }),
  located({
    id: "the-valley",
    canonicalName: "The Valley",
    kind: "valley",
    nationOrRegion: "Central Roshar",
    minimumLod: "region",
    visualization: "valley",
    sourceMapPixel: [482.5, 328.8],
    certainty: "regional",
    coppermindSlug: "Valley",
  }),
  located({
    id: "narak",
    canonicalName: "Narak",
    kind: "ruin",
    nationOrRegion: "Shattered Plains",
    minimumLod: "region",
    visualization: "ruined-city",
    sourceMapPixel: [767.9, 364],
    coppermindSlug: "Stormseat",
    alternateNames: ["Stormseat", "The Listener City"],
  }),
  located({
    id: "hearthstone",
    canonicalName: "Hearthstone",
    kind: "town",
    nationOrRegion: "Sadeas princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    sourceMapPixel: [734, 196.4],
    coppermindSlug: "Hearthstone",
  }),
  located({
    id: "horneater-peaks",
    canonicalName: "Horneater Peaks",
    kind: "mountain-range",
    category: "region",
    nationOrRegion: "Jah Keved",
    minimumLod: "continent",
    visualization: "mountain-range",
    sourceMapPixel: [642.5, 261.5],
    certainty: "regional",
    coppermindSlug: "Horneater_Peaks",
  }),
  located({
    id: "revolar",
    canonicalName: "Revolar",
    kind: "town",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [719.2, 225.9],
    coppermindSlug: "Revolar",
  }),
  located({
    id: "rall-elorim",
    canonicalName: "Rall Elorim",
    kind: "city",
    nationOrRegion: "Iri",
    minimumLod: "region",
    visualization: "port-city",
    sourceMapPixel: [367.3, 115.7],
    coppermindSlug: "Rall_Elorim",
    alternateNames: ["City of Shadows"],
  }),
  located({
    id: "kurth",
    canonicalName: "Kurth",
    kind: "city",
    nationOrRegion: "Rira",
    minimumLod: "region",
    visualization: "port-city",
    sourceMapPixel: [449, 156.5],
    coppermindSlug: "Kurth",
  }),
  located({
    id: "panatham",
    canonicalName: "Panatham",
    kind: "city",
    nationOrRegion: "Babatharnam",
    minimumLod: "region",
    visualization: "market-city",
    sourceMapPixel: [397.4, 245.4],
    coppermindSlug: "Panatham",
  }),
  located({
    id: "azimir",
    canonicalName: "Azimir",
    kind: "city",
    nationOrRegion: "Azir",
    minimumLod: "region",
    visualization: "administrative-city",
    sourceMapPixel: [414.2, 331.3],
    coppermindSlug: "Azimir",
  }),
  located({
    id: "vedenar",
    canonicalName: "Vedenar",
    kind: "city",
    nationOrRegion: "Jah Keved",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [609.8, 334.7],
    coppermindSlug: "Vedenar",
  }),
  located({
    id: "akak",
    canonicalName: "Akak",
    kind: "town",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "port-city",
    sourceMapPixel: [763, 164.7],
    coppermindSlug: "Akak",
  }),
  located({
    id: "varikev",
    canonicalName: "Varikev",
    kind: "town",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [802.2, 212.6],
    coppermindSlug: "Varikev",
  }),
  located({
    id: "shulin",
    canonicalName: "Shulin",
    kind: "town",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [775.9, 257.8],
    coppermindSlug: "Shulin",
  }),
  located({
    id: "karanak",
    canonicalName: "Karanak",
    kind: "town",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "port-city",
    sourceMapPixel: [657.1, 351.2],
    coppermindSlug: "Karanak",
  }),
  located({
    id: "dumadari",
    canonicalName: "Dumadari",
    kind: "town",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [635.7, 334.9],
    coppermindSlug: "Dumadari",
  }),
  located({
    id: "unclaimed-hills",
    canonicalName: "Unclaimed Hills",
    kind: "hills",
    category: "region",
    nationOrRegion: "Eastern Roshar",
    minimumLod: "continent",
    visualization: "hills",
    sourceMapPixel: [794.2, 289.4],
    certainty: "regional",
    coppermindSlug: "Unclaimed_Hills",
  }),
  located({
    id: "dawns-shadow",
    canonicalName: "Dawn's Shadow",
    kind: "landmark",
    nationOrRegion: "Ocean of Origins",
    minimumLod: "region",
    visualization: "rock-formation",
    sourceMapPixel: [814.7, 310],
    coppermindSlug: "Dawn's_Shadow",
  }),
  located({
    id: "ocean-of-origins",
    canonicalName: "Ocean of Origins",
    kind: "ocean",
    nationOrRegion: "Eastern Roshar",
    minimumLod: "continent",
    visualization: "ocean",
    sourceMapPixel: [887.7, 244.6],
    certainty: "regional",
    coppermindSlug: "Ocean_of_Origins",
  }),
  located({
    id: "steamwater-ocean",
    canonicalName: "Steamwater Ocean",
    kind: "ocean",
    nationOrRegion: "Northern Roshar",
    minimumLod: "continent",
    visualization: "ocean",
    sourceMapPixel: [756, 111.3],
    certainty: "regional",
    coppermindSlug: "Steamwater_Ocean",
  }),
  located({
    id: "reshi-sea",
    canonicalName: "Reshi Sea",
    kind: "sea",
    nationOrRegion: "Northern Roshar",
    minimumLod: "continent",
    visualization: "sea",
    sourceMapPixel: [516.3, 178.5],
    certainty: "regional",
    coppermindSlug: "Reshi_Sea",
  }),
  located({
    id: "northern-depths",
    canonicalName: "Northern Depths",
    kind: "ocean",
    nationOrRegion: "Northern Roshar",
    minimumLod: "continent",
    visualization: "ocean",
    sourceMapPixel: [508.8, 57.9],
    certainty: "regional",
    coppermindSlug: "Northern_Depths",
  }),
  located({
    id: "endless-ocean",
    canonicalName: "Endless Ocean",
    kind: "ocean",
    nationOrRegion: "Western Roshar",
    minimumLod: "continent",
    visualization: "ocean",
    sourceMapPixel: [186.4, 123.3],
    certainty: "regional",
    coppermindSlug: "Endless_Ocean",
  }),
  located({
    id: "aimian-sea",
    canonicalName: "Aimian Sea",
    kind: "sea",
    nationOrRegion: "Western Roshar",
    minimumLod: "continent",
    visualization: "sea",
    sourceMapPixel: [237.4, 282],
    certainty: "regional",
    coppermindSlug: "Aimian_Sea",
  }),
  located({
    id: "southern-depths",
    canonicalName: "Southern Depths",
    kind: "ocean",
    nationOrRegion: "Southern Roshar",
    minimumLod: "continent",
    visualization: "ocean",
    sourceMapPixel: [508.2, 456.7],
    certainty: "regional",
    coppermindSlug: "Southern_Depths",
  }),
  located({
    id: "tarat-sea",
    canonicalName: "Tarat Sea",
    kind: "sea",
    nationOrRegion: "Southern Alethkar",
    minimumLod: "continent",
    visualization: "sea",
    sourceMapPixel: [595.6, 350.8],
    certainty: "regional",
    coppermindSlug: "Tarat_Sea",
  }),
  located({
    id: "longbrows-straits",
    canonicalName: "Longbrow's Straits",
    kind: "strait",
    nationOrRegion: "Thaylenah",
    minimumLod: "continent",
    visualization: "strait",
    sourceMapPixel: [615.3, 402.6],
    certainty: "regional",
    coppermindSlug: "Longbrow's_Straits",
  }),
  located({
    id: "klna",
    canonicalName: "Klna",
    kind: "town",
    nationOrRegion: "Thaylenah",
    minimumLod: "region",
    visualization: "port-city",
    sourceMapPixel: [619.1, 407.4],
    coppermindSlug: "Klna",
  }),
  located({
    id: "frostlands",
    canonicalName: "Frostlands",
    kind: "plains",
    category: "region",
    nationOrRegion: "Frostlands",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [709.3, 385.5],
    referencePixel: destinationReferencePixels.frostlands,
    certainty: "regional",
    coppermindSlug: "Frostlands",
  }),
  located({
    id: "shallow-crypts",
    canonicalName: "Shallow Crypts",
    kind: "caves",
    nationOrRegion: "Frostlands",
    minimumLod: "region",
    visualization: "caves",
    sourceMapPixel: [761.3, 426.6],
    certainty: "regional",
    coppermindSlug: "Shallow_Crypts",
  }),
  located({
    id: "northgrip",
    canonicalName: "Northgrip",
    kind: "town",
    nationOrRegion: "Herdaz",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [637.2, 176.8],
    coppermindSlug: "Northgrip",
  }),
  located({
    id: "elanar",
    canonicalName: "Elanar",
    kind: "town",
    nationOrRegion: "Jah Keved",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [585.4, 242.5],
    coppermindSlug: "Elanar",
  }),
  located({
    id: "valath",
    canonicalName: "Valath",
    kind: "town",
    nationOrRegion: "Jah Keved",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [626, 262],
    coppermindSlug: "Valath",
  }),
  located({
    id: "silnasen",
    canonicalName: "Silnasen",
    kind: "town",
    nationOrRegion: "Jah Keved",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [584.6, 312.6],
    coppermindSlug: "Silnasen",
  }),
  located({
    id: "bavland",
    canonicalName: "Bavland",
    kind: "nation",
    nationOrRegion: "Bavland",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [588.5, 288.5],
    certainty: "regional",
    coppermindSlug: "Bavland",
  }),
  located({
    id: "triax",
    canonicalName: "Triax",
    kind: "nation",
    nationOrRegion: "Triax",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [564.4, 328],
    certainty: "regional",
    coppermindSlug: "Triax",
  }),
  located({
    id: "tu-fallia",
    canonicalName: "Tu Fallia",
    kind: "nation",
    nationOrRegion: "Tu Fallia",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [528.3, 332.3],
    certainty: "regional",
    coppermindSlug: "Tu_Fallia",
  }),
  located({
    id: "greater-hexi",
    canonicalName: "Greater Hexi",
    kind: "nation",
    nationOrRegion: "Greater Hexi",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [512.2, 351],
    certainty: "regional",
    coppermindSlug: "Greater_Hexi",
  }),
  located({
    id: "makabak",
    canonicalName: "Makabak",
    kind: "region",
    category: "broad cultural/geographic region",
    nationOrRegion: "Southwestern and south-central Roshar",
    minimumLod: "continent",
    visualization: "nation-label",
    // Regional display anchor at the center of the Makabaki member states,
    // not a claim that this broad cultural region has a single surveyed point.
    referencePixel: [690, 800],
    certainty: "regional",
    coppermindSlug: "Makabak",
    sources: [coppermindSource("Makabak", "Makabak")],
  }),
  located({
    id: "sesemalex-dar",
    canonicalName: "Sesemalex Dar",
    kind: "city",
    nationOrRegion: "Tukar",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [402, 361.8],
    coppermindSlug: "Sesemalex_Dar",
  }),
  located({
    id: "yeddaw",
    canonicalName: "Yeddaw",
    kind: "city",
    nationOrRegion: "Tashikk",
    minimumLod: "region",
    visualization: "market-city",
    sourceMapPixel: [399.9, 337.4],
    coppermindSlug: "Yeddaw",
  }),
  located({
    id: "berizhet",
    canonicalName: "Berizhet",
    kind: "town",
    nationOrRegion: "Liafor",
    minimumLod: "region",
    visualization: "market-city",
    sourceMapPixel: [354.5, 339],
    coppermindSlug: "Berizhet",
  }),
  located({
    id: "yezier",
    canonicalName: "Yezier",
    kind: "nation",
    nationOrRegion: "Yezier",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [356.2, 312.7],
    certainty: "regional",
    coppermindSlug: "Yezier",
  }),
  located({
    id: "alm",
    canonicalName: "Alm",
    kind: "nation",
    nationOrRegion: "Alm",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [329.5, 320.6],
    certainty: "regional",
    coppermindSlug: "Alm",
  }),
  located({
    id: "desh",
    canonicalName: "Desh",
    kind: "nation",
    nationOrRegion: "Desh",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [369.6, 285.7],
    certainty: "regional",
    coppermindSlug: "Desh",
  }),
  located({
    id: "zawfix",
    canonicalName: "Zawfix",
    kind: "town",
    nationOrRegion: "Azir",
    minimumLod: "region",
    visualization: "market-city",
    sourceMapPixel: [465, 298.3],
    coppermindSlug: "Zawfix",
  }),
  located({
    id: "steen",
    canonicalName: "Steen",
    kind: "nation",
    nationOrRegion: "Steen",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [304, 353.4],
    certainty: "regional",
    coppermindSlug: "Steen",
  }),
  located({
    id: "icewater",
    canonicalName: "Icewater",
    kind: "island",
    nationOrRegion: "Southern Roshar",
    minimumLod: "continent",
    visualization: "island",
    sourceMapPixel: [304.9, 386.6],
    certainty: "regional",
    coppermindSlug: "Icewater",
  }),
  located({
    id: "misted-mountains",
    canonicalName: "Misted Mountains",
    kind: "mountain-range",
    nationOrRegion: "Western Roshar",
    minimumLod: "continent",
    visualization: "mountain-range",
    sourceMapPixel: [330.5, 249],
    certainty: "regional",
    coppermindSlug: "Misted_Mountains",
  }),
  located({
    id: "yulay",
    canonicalName: "Yulay",
    kind: "nation",
    nationOrRegion: "Yulay",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [455.1, 277.1],
    certainty: "regional",
    coppermindSlug: "Yulay",
  }),
  located({
    id: "fu-namir",
    canonicalName: "Fu Namir",
    kind: "town",
    nationOrRegion: "Yulay",
    minimumLod: "region",
    visualization: "market-city",
    sourceMapPixel: [494.3, 268.6],
    coppermindSlug: "Fu_Namir",
  }),
  located({
    id: "tu-bayla",
    canonicalName: "Tu Bayla",
    kind: "nation",
    nationOrRegion: "Tu Bayla",
    minimumLod: "continent",
    visualization: "nation-label",
    sourceMapPixel: [541.5, 249.6],
    referencePixel: destinationReferencePixels["tu-bayla"],
    certainty: "regional",
    coppermindSlug: "Tu_Bayla",
  }),
  located({
    id: "ru-parat",
    canonicalName: "Ru Parat",
    kind: "town",
    nationOrRegion: "Tu Bayla",
    minimumLod: "region",
    visualization: "market-city",
    sourceMapPixel: [529.9, 223],
    coppermindSlug: "Ru_Parat",
  }),
  located({
    id: "kasitor",
    canonicalName: "Kasitor",
    kind: "town",
    nationOrRegion: "Iri",
    minimumLod: "region",
    visualization: "fortified-city",
    sourceMapPixel: [324, 154.7],
    coppermindSlug: "Kasitor",
  }),
  located({
    id: "eila",
    canonicalName: "Eila",
    kind: "ruin",
    nationOrRegion: "Iri",
    minimumLod: "region",
    visualization: "ruined-city",
    sourceMapPixel: [331.3, 205.7],
    coppermindSlug: "Eila",
  }),
  located({
    id: "quili",
    canonicalName: "Quili",
    kind: "island",
    nationOrRegion: "Reshi Isles",
    minimumLod: "region",
    visualization: "island",
    sourceMapPixel: [431.6, 94.7],
    coppermindSlug: "Quili",
  }),
  located({
    id: "abri",
    canonicalName: "Abri",
    kind: "island",
    nationOrRegion: "Reshi Isles",
    minimumLod: "region",
    visualization: "island",
    sourceMapPixel: [476.3, 88.2],
    coppermindSlug: "Abri",
  }),
  located({
    id: "kadrix",
    canonicalName: "Kadrix",
    kind: "island",
    nationOrRegion: "Reshi Isles",
    minimumLod: "region",
    visualization: "island",
    sourceMapPixel: [501.1, 86.9],
    coppermindSlug: "Kadrix",
  }),
  located({
    id: "arak",
    canonicalName: "Arak",
    kind: "island",
    nationOrRegion: "Reshi Isles",
    minimumLod: "region",
    visualization: "island",
    sourceMapPixel: [658.3, 125.1],
    coppermindSlug: "Arak",
  }),
  located({
    id: "sumi",
    canonicalName: "Sumi",
    kind: "island",
    nationOrRegion: "Reshi Isles",
    minimumLod: "region",
    visualization: "island",
    sourceMapPixel: [644.9, 134.7],
    coppermindSlug: "Sumi",
  }),

  // Novel-important local exteriors and geographic features not represented as
  // distinct points in the source map.
  located({
    id: "akinah",
    canonicalName: "Akinah",
    kind: "ruin",
    nationOrRegion: "Aimia",
    minimumLod: "city",
    visualization: "ruined-city",
    referencePixel: [115, 700],
    certainty: "regional",
    coppermindSlug: "Akinah",
    sources: [coppermindSource("Akinah", "Akinah")],
  }),
  located({
    id: "alethi-warcamps",
    canonicalName: "Alethi Warcamps",
    kind: "landmark",
    nationOrRegion: "Shattered Plains",
    minimumLod: "city",
    visualization: "warcamp",
    referencePixel: [1515, 780],
    certainty: "regional",
    coppermindSlug: "Alethi_warcamps",
    sources: [coppermindSource("Alethi_warcamps", "Alethi Warcamps")],
  }),
  unknown({
    id: "palanaeum",
    canonicalName: "Palanaeum",
    kind: "institution",
    nationOrRegion: "Inside the Conclave, Kharbranth; no separate exterior",
    minimumLod: "street",
    visualization: "library",
    coppermindSlug: "Palanaeum",
    sources: [coppermindSource("Palanaeum", "Palanaeum")],
  }),
  located({
    id: "kharbranth-conclave",
    canonicalName: "Kharbranth Conclave",
    kind: "institution",
    nationOrRegion: "Kharbranth",
    minimumLod: "street",
    visualization: "palace",
    referencePixel: destinationReferencePixels.kharbranth,
    certainty: "regional",
    coppermindSlug: "Conclave",
    sources: [coppermindSource("Conclave", "Kharbranth Conclave")],
  }),
  unknown({
    id: "taravangian-hospital",
    canonicalName: "Silent Gatherers' Hidden Hospital",
    kind: "institution",
    nationOrRegion: "Inside the Conclave, Kharbranth; no exterior",
    minimumLod: "street",
    visualization: "hospital",
    coppermindSlug: "Kharbranth",
    sources: [coppermindSource("Kharbranth", "Kharbranth")],
  }),
  located({
    id: "kholinar-palace",
    canonicalName: "Kholinar Palace",
    kind: "institution",
    nationOrRegion: "Kholinar, Alethkar",
    minimumLod: "street",
    visualization: "palace",
    referencePixel: destinationReferencePixels.kholinar,
    certainty: "regional",
    coppermindSlug: "Kholinar_Palace",
    sources: [coppermindSource("Kholinar_Palace", "Kholinar Palace")],
  }),
  located({
    id: "sunwalk",
    canonicalName: "Sunwalk",
    kind: "landmark",
    nationOrRegion: "Kholinar, Alethkar",
    minimumLod: "street",
    visualization: "processional-way",
    referencePixel: destinationReferencePixels.kholinar,
    certainty: "regional",
    coppermindSlug: "Sunwalk",
    sources: [coppermindSource("Sunwalk", "Sunwalk")],
  }),
  located({
    id: "thaylen-field",
    canonicalName: "Thaylen Field",
    kind: "plains",
    nationOrRegion: "Thaylen City, Thaylenah",
    minimumLod: "city",
    visualization: "hills",
    referencePixel: [1115, 960],
    certainty: "regional",
    coppermindSlug: "Thaylen_Field",
    sources: [coppermindSource("Thaylen_Field", "Thaylen Field")],
  }),
  located({
    id: "jokasha-monastery",
    canonicalName: "Jokasha Monastery",
    kind: "institution",
    nationOrRegion: "Western Horneater Peaks, Jah Keved",
    minimumLod: "city",
    visualization: "monastery",
    referencePixel: [1205, 545],
    certainty: "regional",
    coppermindSlug: "Jokasha_Monastery",
    sources: [coppermindSource("Jokasha_Monastery", "Jokasha Monastery")],
  }),
  located({
    id: "cultivations-perpendicularity",
    canonicalName: "Cultivation's Perpendicularity",
    kind: "landmark",
    nationOrRegion: "Horneater Peaks",
    minimumLod: "city",
    visualization: "shallow-lake",
    referencePixel: [1240, 570],
    certainty: "regional",
    coppermindSlug: "Cultivation's_Perpendicularity",
    sources: [
      coppermindSource(
        "Cultivation's_Perpendicularity",
        "Cultivation's Perpendicularity",
      ),
    ],
  }),
  located({
    id: "davar-estate",
    canonicalName: "Davar Estate",
    kind: "institution",
    nationOrRegion: "Jah Keved",
    minimumLod: "city",
    visualization: "palace",
    referencePixel: [1175, 525],
    certainty: "regional",
    coppermindSlug: "Davar_manor",
    sources: [coppermindSource("Davar_manor", "House Davar")],
  }),
  located({
    id: "ishars-field",
    canonicalName: "Ishar's Field",
    kind: "plains",
    nationOrRegion: "Emul",
    minimumLod: "city",
    visualization: "hills",
    referencePixel: destinationReferencePixels.emul,
    certainty: "regional",
    coppermindSlug: "Ishar's_Field",
    sources: [coppermindSource("Ishar's_Field", "Ishar's Field")],
  }),
  located({
    id: "windrunner-river",
    canonicalName: "Windrunner River",
    kind: "river",
    nationOrRegion: "Northern Alethkar",
    minimumLod: "continent",
    visualization: "river",
    referencePixel: [1460, 455],
    certainty: "regional",
    coppermindSlug: "Windrunner_River",
    sources: [coppermindSource("Windrunner_River", "Windrunner River")],
  }),
  located({
    id: "deathbend-river",
    canonicalName: "Deathbend River",
    kind: "river",
    nationOrRegion: "Eastern and southern Alethkar",
    minimumLod: "continent",
    visualization: "river",
    referencePixel: [1490, 690],
    certainty: "regional",
    coppermindSlug: "Deathbend_River",
    sources: [coppermindSource("Deathbend_River", "Deathbend River")],
  }),
  located({
    id: "icingway-river",
    canonicalName: "Icingway River",
    kind: "river",
    nationOrRegion: "Alethkar",
    minimumLod: "region",
    visualization: "river",
    referencePixel: [1450, 665],
    certainty: "regional",
    coppermindSlug: "Icingway_River",
    sources: [coppermindSource("Icingway_River", "Icingway River")],
  }),
  located({
    id: "river-vandonas",
    canonicalName: "River Vandonas",
    kind: "river",
    nationOrRegion: "Alethi Warcamps, Shattered Plains",
    minimumLod: "city",
    visualization: "river",
    referencePixel: [1515, 790],
    certainty: "regional",
    coppermindSlug: "River_Vandonas",
    sources: [coppermindSource("River_Vandonas", "River Vandonas")],
  }),
  unknown({
    id: "feverstone-keep",
    canonicalName: "Feverstone Keep",
    kind: "ruin",
    nationOrRegion: "Roshar; exact region unknown",
    minimumLod: "city",
    visualization: "ruined-city",
    coppermindSlug: "Feverstone_Keep",
  }),
  unknown({
    id: "uvara",
    canonicalName: "Uvara",
    kind: "island",
    nationOrRegion: "Ocean around Roshar; exact position unknown",
    minimumLod: "region",
    visualization: "island",
    coppermindSlug: "Uvara",
  }),
  unknown({
    id: "puulis-lighthouse",
    canonicalName: "Puuli's Lighthouse",
    kind: "institution",
    nationOrRegion: "Western Roshar; exact coast unknown",
    minimumLod: "city",
    visualization: "lighthouse",
    coppermindSlug: "Puuli's_lighthouse",
  }),
  ...shinovarGazetteer,
  ...cityPlanGazetteer,
  ...literaryPlaceGazetteer,
] as const;

export const placeableGazetteer = rosharGazetteer.filter(
  (place) => place.renderable,
);

export const unknownGazetteer = rosharGazetteer.filter(
  (place) => !place.renderable,
);

export const gazetteerById = new Map(
  rosharGazetteer.map((place) => [place.id, place]),
);

export {
  ROSHAR_MAP_LANGUAGE_URL,
  ROSHAR_MAP_LOCATIONS_URL,
};
