import type { DetailLevel } from "../types";
import { referencePixelToGazetteerWorld } from "./transform";
import { defaultGazetteerCategory } from "./types";
import type {
  GazetteerKind,
  GazetteerPlace,
  GazetteerSource,
  VisualizationArchetype,
} from "./types";

const ALETHKAR_SOURCE: GazetteerSource = {
  title: "The Coppermind — Alethkar (includes Isaac Stewart's Map of Alethkar)",
  url: "https://coppermind.net/wiki/Alethkar",
};

function coppermind(slug: string, title: string): GazetteerSource {
  return {
    title: `The Coppermind — ${title}`,
    url: `https://coppermind.net/wiki/${slug}`,
  };
}

interface RegionalPlaceInput {
  id: string;
  canonicalName: string;
  kind: GazetteerKind;
  nationOrRegion: string;
  minimumLod: DetailLevel;
  visualization: VisualizationArchetype;
  referencePixel: readonly [number, number];
  sourceSlug: string;
  parentLocationId?: string;
  alternateNames?: readonly string[];
  supportingSources?: readonly GazetteerSource[];
}

/**
 * These display anchors are deliberately regional rather than geodetic.
 *
 * Each source identifies a parent city, country, or directional subregion, but
 * not a point on the project's continental raster. Keeping sourceMapPixel null
 * and certainty "regional" prevents a rounded marker from being mistaken for
 * an exact canonical coordinate.
 */
function regional(input: RegionalPlaceInput): GazetteerPlace {
  return {
    id: input.id,
    canonicalName: input.canonicalName,
    parentLocationId: input.parentLocationId,
    kind: input.kind,
    category: defaultGazetteerCategory(input.kind),
    nationOrRegion: input.nationOrRegion,
    certainty: "regional",
    minimumLod: input.minimumLod,
    visualization: input.visualization,
    sourceMapPixel: null,
    referencePixel: input.referencePixel,
    world: referencePixelToGazetteerWorld(input.referencePixel),
    renderable: true,
    alternateNames: input.alternateNames,
    sources: [
      coppermind(input.sourceSlug, input.canonicalName),
      ...(input.supportingSources ?? []),
    ],
  };
}

const anchors = {
  alethkar: [1480, 600],
  aladar: [1490, 405],
  bethab: [1360, 680],
  hatham: [1340, 585],
  kholin: [1580, 515],
  roion: [1640, 410],
  ruthar: [1375, 505],
  sadeas: [1380, 430],
  sebarial: [1485, 675],
  thanadal: [1450, 575],
  vamah: [1415, 455],
  crownlands: [1570, 650],
  kholinar: [1405, 540],
  bavland: [1096.5580307442997, 629.3396958063553],
  jahKeved: [1170, 535],
  azir: [620, 680],
  azirNorthwest: [555, 640],
  azirCentral: [625, 700],
  azirEast: [690, 710],
  emul: [750, 760],
  yeddaw: [614.7339076470396, 754.3092894123872],
  purelake: [800, 540],
  shatteredPlains: [1575, 815],
  urithiru: [830, 700],
  kharbranth: [1105, 885],
  rallElorim: [577.0069160546087, 230.53884052141635],
  horneaterPeaks: [1230.6821542994694, 561.129814599768],
  thaylenCity: [1090, 970],
  shinovarSouth: [380, 680],
  shinovarSoutheast: [455, 665],
} as const satisfies Record<string, readonly [number, number]>;

const alethiPrincedoms: readonly GazetteerPlace[] = [
  regional({
    id: "aladar-princedom",
    canonicalName: "Aladar princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.aladar,
    sourceSlug: "Aladar_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "bethab-princedom",
    canonicalName: "Bethab princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.bethab,
    sourceSlug: "Bethab_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "hatham-princedom",
    canonicalName: "Hatham princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.hatham,
    sourceSlug: "Hatham_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "kholin-princedom",
    canonicalName: "Kholin princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.kholin,
    sourceSlug: "Kholin_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "roion-princedom",
    canonicalName: "Roion princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.roion,
    sourceSlug: "Roion_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "ruthar-princedom",
    canonicalName: "Ruthar princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.ruthar,
    sourceSlug: "Ruthar_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "sadeas-princedom",
    canonicalName: "Sadeas princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.sadeas,
    sourceSlug: "Sadeas_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "sebarial-princedom",
    canonicalName: "Sebarial princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.sebarial,
    sourceSlug: "Sebarial_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "thanadal-princedom",
    canonicalName: "Thanadal princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.thanadal,
    sourceSlug: "Thanadal_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "vamah-princedom",
    canonicalName: "Vamah princedom",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.vamah,
    sourceSlug: "Vamah_princedom",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "eastern-crownlands",
    canonicalName: "Eastern Crownlands",
    kind: "landmark",
    nationOrRegion: "Alethkar",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.crownlands,
    sourceSlug: "Eastern_Crownlands",
    supportingSources: [ALETHKAR_SOURCE],
  }),
] as const;

const alethiSettlements: readonly GazetteerPlace[] = [
  regional({
    id: "akanny",
    canonicalName: "Akanny",
    kind: "valley",
    nationOrRegion: "Sadeas princedom, Alethkar",
    minimumLod: "region",
    visualization: "valley",
    referencePixel: anchors.sadeas,
    sourceSlug: "Akanny",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "dalilak",
    canonicalName: "Dalilak",
    kind: "town",
    nationOrRegion: "Aladar princedom, Alethkar",
    minimumLod: "region",
    visualization: "fortified-city",
    referencePixel: anchors.aladar,
    sourceSlug: "Dalilak",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "danidan",
    canonicalName: "Danidan",
    kind: "town",
    nationOrRegion: "Ruthar princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.ruthar,
    sourceSlug: "Danidan",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "darkhill",
    canonicalName: "Darkhill",
    kind: "town",
    nationOrRegion: "Hatham princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.hatham,
    sourceSlug: "Darkhill",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "davinar",
    canonicalName: "Davinar",
    kind: "town",
    nationOrRegion: "Thanadal princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.thanadal,
    sourceSlug: "Davinar",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "farcoast",
    canonicalName: "Farcoast",
    kind: "town",
    nationOrRegion: "Vamah princedom, Alethkar",
    minimumLod: "region",
    visualization: "port-city",
    referencePixel: anchors.vamah,
    sourceSlug: "Farcoast",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "hobbleken",
    canonicalName: "Hobbleken",
    kind: "village",
    nationOrRegion: "Sadeas princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.sadeas,
    sourceSlug: "Hobbleken",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "hornhollow",
    canonicalName: "Hornhollow",
    kind: "village",
    nationOrRegion: "Akanny, Sadeas princedom, Alethkar",
    minimumLod: "city",
    visualization: "village",
    referencePixel: anchors.sadeas,
    sourceSlug: "Hornhollow",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "inkwell",
    canonicalName: "Inkwell",
    kind: "town",
    nationOrRegion: "Central Alethkar",
    minimumLod: "region",
    visualization: "market-city",
    referencePixel: anchors.alethkar,
    sourceSlug: "Inkwell_(town)",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "kelathar",
    canonicalName: "Kelathar",
    kind: "town",
    nationOrRegion: "Ruthar princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.ruthar,
    sourceSlug: "Kelathar",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "mourns-vault",
    canonicalName: "Mourn's Vault",
    kind: "village",
    nationOrRegion: "Sadeas princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.sadeas,
    sourceSlug: "Mourn%27s_Vault",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "rashir",
    canonicalName: "Rashir",
    kind: "town",
    nationOrRegion: "Sebarial princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.sebarial,
    sourceSlug: "Rashir",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "relanas",
    canonicalName: "Relanas",
    kind: "town",
    nationOrRegion: "Roion princedom, Alethkar",
    minimumLod: "region",
    visualization: "port-city",
    referencePixel: anchors.roion,
    sourceSlug: "Relanas",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "savalashi",
    canonicalName: "Savalashi",
    kind: "town",
    nationOrRegion: "Thanadal princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.thanadal,
    sourceSlug: "Savalashi",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "shamel",
    canonicalName: "Shamel",
    kind: "town",
    nationOrRegion: "Hatham princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.hatham,
    sourceSlug: "Shamel",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "shorsebroon",
    canonicalName: "Shorsebroon",
    kind: "village",
    nationOrRegion: "Sadeas princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.sadeas,
    sourceSlug: "Shorsebroon",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "stringken",
    canonicalName: "Stringken",
    kind: "village",
    nationOrRegion: "Sadeas princedom, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.sadeas,
    sourceSlug: "Stringken",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "talinar",
    canonicalName: "Talinar",
    kind: "town",
    nationOrRegion: "Alethkar (princedom unknown)",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.alethkar,
    sourceSlug: "Talinar",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "tomat",
    canonicalName: "Tomat",
    kind: "town",
    nationOrRegion: "Sadeas princedom, Alethkar",
    minimumLod: "region",
    visualization: "fortified-city",
    referencePixel: anchors.sadeas,
    sourceSlug: "Tomat",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "vedelliar",
    canonicalName: "Vedelliar",
    kind: "town",
    nationOrRegion: "Eastern Crownlands, Alethkar",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.crownlands,
    sourceSlug: "Vedelliar",
    supportingSources: [ALETHKAR_SOURCE],
  }),
] as const;

const alethiFeatures: readonly GazetteerPlace[] = [
  regional({
    id: "bay-of-elibath",
    canonicalName: "Bay of Elibath",
    kind: "sea",
    nationOrRegion: "Northern Alethkar",
    minimumLod: "continent",
    visualization: "sea",
    referencePixel: [1510, 350],
    sourceSlug: "Bay_of_Elibath",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "hoel-bay",
    canonicalName: "Hoel Bay",
    kind: "sea",
    nationOrRegion: "Roion princedom, Alethkar",
    minimumLod: "continent",
    visualization: "sea",
    referencePixel: [1690, 385],
    sourceSlug: "Hoel_Bay",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "nightstream-sea",
    canonicalName: "Nightstream Sea",
    kind: "sea",
    nationOrRegion: "Northern Alethkar",
    minimumLod: "continent",
    visualization: "sea",
    referencePixel: [1600, 350],
    sourceSlug: "Nightstream_Sea",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "sea-of-spears",
    canonicalName: "Sea of Spears",
    kind: "sea",
    nationOrRegion: "Central Alethkar",
    minimumLod: "continent",
    visualization: "sea",
    referencePixel: [1480, 625],
    sourceSlug: "Sea_of_Spears",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "mevan-bay",
    canonicalName: "Mevan Bay",
    kind: "sea",
    nationOrRegion: "Southwestern Alethkar",
    minimumLod: "continent",
    visualization: "sea",
    referencePixel: [1360, 765],
    sourceSlug: "Mevan_Bay",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "sunmaker-mountains",
    canonicalName: "Sunmaker Mountains",
    kind: "mountain-range",
    nationOrRegion: "Central Alethkar",
    minimumLod: "continent",
    visualization: "mountain-range",
    referencePixel: [1420, 545],
    sourceSlug: "Sunmaker_Mountains",
    supportingSources: [ALETHKAR_SOURCE],
  }),
  regional({
    id: "fallen-tower",
    canonicalName: "Fallen Tower",
    parentLocationId: "kholinar",
    kind: "institution",
    nationOrRegion: "Kholinar, Alethkar",
    minimumLod: "street",
    visualization: "market-city",
    referencePixel: anchors.kholinar,
    sourceSlug: "Fallen_Tower",
  }),
  regional({
    id: "rockfall",
    canonicalName: "Rockfall",
    parentLocationId: "kholinar",
    kind: "landmark",
    nationOrRegion: "Kholinar, Alethkar",
    minimumLod: "street",
    visualization: "palace",
    referencePixel: anchors.kholinar,
    sourceSlug: "Rockfall",
  }),
] as const;

const bavlandPlaces: readonly GazetteerPlace[] = [
  regional({
    id: "bornwater",
    canonicalName: "Bornwater",
    kind: "town",
    nationOrRegion: "Bavland, Jah Keved",
    minimumLod: "region",
    visualization: "mountain-city",
    referencePixel: anchors.bavland,
    sourceSlug: "Bornwater",
    supportingSources: [coppermind("Bavland", "Bavland")],
  }),
  regional({
    id: "ironsway",
    canonicalName: "Ironsway",
    kind: "town",
    nationOrRegion: "Bavland, Jah Keved",
    minimumLod: "region",
    visualization: "market-city",
    referencePixel: anchors.bavland,
    sourceSlug: "Ironsway",
    supportingSources: [coppermind("Bavland", "Bavland")],
  }),
  regional({
    id: "kneespike",
    canonicalName: "Kneespike",
    kind: "city",
    nationOrRegion: "Bavland, Jah Keved",
    minimumLod: "region",
    visualization: "mountain-city",
    referencePixel: anchors.bavland,
    sourceSlug: "Kneespike",
    supportingSources: [coppermind("Bavland", "Bavland")],
  }),
  regional({
    id: "staplind",
    canonicalName: "Staplind",
    kind: "village",
    nationOrRegion: "Bavland, Jah Keved",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.bavland,
    sourceSlug: "Staplind",
    supportingSources: [coppermind("Bavland", "Bavland")],
  }),
] as const;

const makabakamPlaces: readonly GazetteerPlace[] = [
  regional({
    id: "mazzu",
    canonicalName: "Mazzu",
    kind: "town",
    nationOrRegion: "Northwestern Azir",
    minimumLod: "region",
    visualization: "administrative-city",
    referencePixel: anchors.azirNorthwest,
    sourceSlug: "Mazzu",
    supportingSources: [coppermind("Azir", "Azir")],
  }),
  regional({
    id: "zodruf",
    canonicalName: "Zodruf",
    kind: "town",
    nationOrRegion: "Central Azir",
    minimumLod: "region",
    visualization: "administrative-city",
    referencePixel: anchors.azirCentral,
    sourceSlug: "Zodruf",
    supportingSources: [coppermind("Azir", "Azir")],
  }),
  regional({
    id: "owd",
    canonicalName: "Owd",
    kind: "town",
    nationOrRegion: "Eastern Azir, near the Emuli border",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.azirEast,
    sourceSlug: "Owd",
    supportingSources: [coppermind("Azir", "Azir")],
  }),
  regional({
    id: "benru",
    canonicalName: "Benru",
    kind: "town",
    nationOrRegion: "Yulay, on the Azir border",
    minimumLod: "region",
    visualization: "market-city",
    referencePixel: anchors.azirEast,
    sourceSlug: "Benru",
    supportingSources: [coppermind("Azir", "Azir")],
  }),
  regional({
    id: "berqq",
    canonicalName: "Berqq",
    kind: "town",
    nationOrRegion: "Yulay, on the Azir border",
    minimumLod: "region",
    visualization: "market-city",
    referencePixel: anchors.azirEast,
    sourceSlug: "Berqq",
    supportingSources: [coppermind("Azir", "Azir")],
  }),
  regional({
    id: "laqqi",
    canonicalName: "Laqqi",
    kind: "village",
    nationOrRegion: "Central Emul",
    minimumLod: "region",
    visualization: "warcamp",
    referencePixel: anchors.emul,
    sourceSlug: "Laqqi",
  }),
  regional({
    id: "grand-indicium",
    canonicalName: "Grand Indicium",
    kind: "institution",
    nationOrRegion: "Yeddaw, Tashikk",
    minimumLod: "street",
    visualization: "palace",
    referencePixel: anchors.yeddaw,
    sourceSlug: "Grand_Indicium",
  }),
] as const;

const purelakePlaces: readonly GazetteerPlace[] = [
  regional({
    id: "fu-abra",
    canonicalName: "Fu Abra",
    kind: "village",
    nationOrRegion: "Purelake",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.purelake,
    sourceSlug: "Fu_Abra",
    supportingSources: [coppermind("Purelake", "Purelake")],
  }),
  regional({
    id: "fu-albast",
    canonicalName: "Fu Albast",
    kind: "village",
    nationOrRegion: "Purelake",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.purelake,
    sourceSlug: "Fu_Albast",
    supportingSources: [coppermind("Purelake", "Purelake")],
  }),
  regional({
    id: "fu-moorin",
    canonicalName: "Fu Moorin",
    kind: "village",
    nationOrRegion: "Purelake",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.purelake,
    sourceSlug: "Fu_Moorin",
    supportingSources: [coppermind("Purelake", "Purelake")],
  }),
  regional({
    id: "fu-ralis",
    canonicalName: "Fu Ralis",
    kind: "village",
    nationOrRegion: "Purelake",
    minimumLod: "region",
    visualization: "village",
    referencePixel: anchors.purelake,
    sourceSlug: "Fu_Ralis",
    supportingSources: [coppermind("Purelake", "Purelake")],
  }),
  regional({
    id: "holy-grotto",
    canonicalName: "Holy grotto",
    kind: "landmark",
    nationOrRegion: "Purelake",
    minimumLod: "city",
    visualization: "caves",
    referencePixel: anchors.purelake,
    sourceSlug: "Holy_grotto",
    supportingSources: [coppermind("Purelake", "Purelake")],
  }),
] as const;

const shatteredPlainsPlaces: readonly GazetteerPlace[] = [
  regional({
    id: "honor-chasm",
    canonicalName: "Honor Chasm",
    parentLocationId: "shattered-plains",
    kind: "landmark",
    nationOrRegion: "Alethi Warcamps, Shattered Plains",
    minimumLod: "city",
    visualization: "shattered-plains",
    referencePixel: anchors.shatteredPlains,
    sourceSlug: "Honor_Chasm",
  }),
  regional({
    id: "feasting-basin",
    canonicalName: "Feasting basin",
    parentLocationId: "shattered-plains",
    kind: "landmark",
    nationOrRegion: "Alethi Warcamps, Shattered Plains",
    minimumLod: "street",
    visualization: "warcamp",
    referencePixel: anchors.shatteredPlains,
    sourceSlug: "Feasting_basin",
  }),
  regional({
    id: "outer-market",
    canonicalName: "Outer Market",
    parentLocationId: "shattered-plains",
    kind: "landmark",
    nationOrRegion: "Alethi Warcamps, Shattered Plains",
    minimumLod: "street",
    visualization: "market-city",
    referencePixel: anchors.shatteredPlains,
    sourceSlug: "Outer_Market",
  }),
  regional({
    id: "pinnacle",
    canonicalName: "Pinnacle",
    parentLocationId: "shattered-plains",
    kind: "institution",
    nationOrRegion: "Alethi Warcamps, Shattered Plains",
    minimumLod: "street",
    visualization: "palace",
    referencePixel: anchors.shatteredPlains,
    sourceSlug: "Pinnacle",
  }),
  regional({
    id: "little-herdaz",
    canonicalName: "Little Herdaz",
    parentLocationId: "shattered-plains",
    kind: "landmark",
    nationOrRegion: "Sebarial warcamp, Shattered Plains",
    minimumLod: "street",
    visualization: "market-city",
    referencePixel: anchors.shatteredPlains,
    sourceSlug: "Little_Herdaz",
  }),
  regional({
    id: "tower-plateau",
    canonicalName: "Tower plateau",
    parentLocationId: "shattered-plains",
    kind: "landmark",
    nationOrRegion: "Shattered Plains",
    minimumLod: "city",
    visualization: "shattered-plains",
    referencePixel: anchors.shatteredPlains,
    sourceSlug: "Tower_(Roshar)",
    alternateNames: ["The Tower"],
  }),
  regional({
    id: "ornery-chull",
    canonicalName: "Ornery Chull",
    parentLocationId: "shattered-plains",
    kind: "institution",
    nationOrRegion: "Sadeas warcamp, Shattered Plains",
    minimumLod: "street",
    visualization: "market-city",
    referencePixel: anchors.shatteredPlains,
    sourceSlug: "Ornery_Chull",
  }),
  regional({
    id: "pinnacle-dueling-arena",
    canonicalName: "Pinnacle Dueling Arena",
    parentLocationId: "shattered-plains",
    kind: "landmark",
    nationOrRegion: "Alethi Warcamps, Shattered Plains",
    minimumLod: "street",
    visualization: "warcamp",
    referencePixel: anchors.shatteredPlains,
    sourceSlug: "Dueling_Arena",
    alternateNames: ["Warcamp Dueling Arena"],
  }),
] as const;

const cityInteriorPlaces: readonly GazetteerPlace[] = [
  regional({
    id: "breakaway",
    canonicalName: "Breakaway",
    parentLocationId: "urithiru",
    kind: "landmark",
    nationOrRegion: "Urithiru",
    minimumLod: "city",
    visualization: "market-city",
    referencePixel: anchors.urithiru,
    sourceSlug: "Breakaway",
  }),
  regional({
    id: "ten-rings",
    canonicalName: "Ten Rings",
    parentLocationId: "urithiru",
    kind: "landmark",
    nationOrRegion: "Breakaway, Urithiru",
    minimumLod: "street",
    visualization: "market-city",
    referencePixel: anchors.urithiru,
    sourceSlug: "Ten_Rings",
  }),
  regional({
    id: "alls-alley",
    canonicalName: "All's Alley",
    parentLocationId: "urithiru",
    kind: "institution",
    nationOrRegion: "Breakaway, Urithiru",
    minimumLod: "street",
    visualization: "market-city",
    referencePixel: anchors.urithiru,
    sourceSlug: "All%27s_Alley",
  }),
  regional({
    id: "urithiru-gem-archive",
    canonicalName: "Urithiru gem archive",
    parentLocationId: "urithiru",
    kind: "institution",
    nationOrRegion: "Urithiru",
    minimumLod: "street",
    visualization: "library",
    referencePixel: anchors.urithiru,
    sourceSlug: "Urithiru_gem_archive",
  }),
  regional({
    id: "great-concourse-kharbranth",
    canonicalName: "Great Concourse of Kharbranth",
    parentLocationId: "kharbranth",
    kind: "institution",
    nationOrRegion: "Kharbranth",
    minimumLod: "street",
    visualization: "hospital",
    referencePixel: anchors.kharbranth,
    sourceSlug: "Great_Concourse_of_Kharbranth",
  }),
  regional({
    id: "school-of-storms",
    canonicalName: "School of Storms",
    parentLocationId: "kharbranth",
    kind: "institution",
    nationOrRegion: "Kharbranth (near the Palanaeum; exact site unconfirmed)",
    minimumLod: "street",
    visualization: "library",
    referencePixel: anchors.kharbranth,
    sourceSlug: "School_of_Storms",
  }),
  regional({
    id: "ralinsa",
    canonicalName: "Ralinsa",
    parentLocationId: "kharbranth",
    kind: "landmark",
    nationOrRegion: "Kharbranth",
    minimumLod: "street",
    visualization: "processional-way",
    referencePixel: anchors.kharbranth,
    sourceSlug: "Ralinsa",
  }),
  regional({
    id: "thaylen-gemstone-reserve",
    canonicalName: "Thaylen Gemstone Reserve",
    parentLocationId: "thaylen-city",
    kind: "institution",
    nationOrRegion: "Thaylen City",
    minimumLod: "street",
    visualization: "palace",
    referencePixel: anchors.thaylenCity,
    sourceSlug: "Thaylen_Gemstone_Reserve",
  }),
] as const;

const otherRegionalPlaces: readonly GazetteerPlace[] = [
  regional({
    id: "valam-princedom",
    canonicalName: "Valam princedom",
    kind: "landmark",
    nationOrRegion: "Jah Keved (subnational position unknown)",
    minimumLod: "continent",
    visualization: "nation-label",
    referencePixel: anchors.jahKeved,
    sourceSlug: "Valam_princedom",
  }),
  regional({
    id: "silent-mount",
    canonicalName: "Silent Mount",
    kind: "mountain-range",
    nationOrRegion: "Jah Keved",
    minimumLod: "region",
    visualization: "mountain-range",
    referencePixel: anchors.jahKeved,
    sourceSlug: "Silent_Mount",
  }),
  regional({
    id: "stormfalls",
    canonicalName: "Stormfalls",
    kind: "landmark",
    nationOrRegion: "Rall Elorim, Iri",
    minimumLod: "city",
    visualization: "rock-formation",
    referencePixel: anchors.rallElorim,
    sourceSlug: "Stormfalls",
  }),
  regional({
    id: "horneater-oceans",
    canonicalName: "Horneater Oceans",
    kind: "lake",
    nationOrRegion: "Horneater Peaks",
    minimumLod: "city",
    visualization: "shallow-lake",
    referencePixel: anchors.horneaterPeaks,
    sourceSlug: "Horneater_Oceans",
  }),
  regional({
    id: "valley-of-truth",
    canonicalName: "Valley of Truth",
    parentLocationId: "shinovar",
    kind: "valley",
    nationOrRegion: "Coastal Shinovar",
    minimumLod: "region",
    visualization: "valley",
    referencePixel: anchors.shinovarSouth,
    sourceSlug: "Valley_of_Truth",
  }),
  regional({
    id: "nirovah-valley",
    canonicalName: "Nirovah Valley",
    parentLocationId: "shinovar",
    kind: "valley",
    nationOrRegion: "Southeastern Shinovar",
    minimumLod: "region",
    visualization: "valley",
    referencePixel: anchors.shinovarSoutheast,
    sourceSlug: "Nirovah_Valley",
  }),
  regional({
    id: "disons-valley",
    canonicalName: "Dison's Valley",
    parentLocationId: "shinovar",
    kind: "valley",
    nationOrRegion: "Southeastern Shinovar",
    minimumLod: "region",
    visualization: "valley",
    referencePixel: anchors.shinovarSoutheast,
    sourceSlug: "Dison%27s_Valley",
  }),
] as const;

/**
 * Book- and official-inset-supported gaps not already present in catalog.ts,
 * shinovar.ts, or cityPlans.ts.
 */
export const literaryPlaceGazetteer: readonly GazetteerPlace[] = [
  ...alethiPrincedoms,
  ...alethiSettlements,
  ...alethiFeatures,
  ...bavlandPlaces,
  ...makabakamPlaces,
  ...purelakePlaces,
  ...shatteredPlainsPlaces,
  ...cityInteriorPlaces,
  ...otherRegionalPlaces,
] as const;

export type LiteraryPlaceExclusionReason =
  | "unknown-physical-location"
  | "cognitive-realm"
  | "already-cataloged-alias";

export interface LiteraryPlaceExclusion {
  canonicalName: string;
  reason: LiteraryPlaceExclusionReason;
  note: string;
  sources: readonly GazetteerSource[];
}

/**
 * Audited names deliberately omitted from the placeable layer.
 */
export const literaryPlaceExclusions: readonly LiteraryPlaceExclusion[] = [
  {
    canonicalName: "Abamabar",
    reason: "unknown-physical-location",
    note: "The text establishes a long journey to Urithiru, not a containing modern region.",
    sources: [coppermind("Abamabar", "Abamabar")],
  },
  {
    canonicalName: "Feverstone Keep",
    reason: "unknown-physical-location",
    note: "Already retained as unplaceable in the core catalog; no responsible regional anchor is known.",
    sources: [coppermind("Feverstone_Keep", "Feverstone Keep")],
  },
  {
    canonicalName: "Uvara",
    reason: "unknown-physical-location",
    note: "Already retained as unplaceable in the core catalog.",
    sources: [coppermind("Uvara", "Uvara")],
  },
  {
    canonicalName: "Puuli's lighthouse",
    reason: "unknown-physical-location",
    note: "Already retained as unplaceable in the core catalog.",
    sources: [coppermind("Puuli", "Puuli")],
  },
  {
    canonicalName: "Haka'alaku",
    reason: "cognitive-realm",
    note: "A Shadesmar settlement, not a Physical-Realm map marker.",
    sources: [coppermind("Haka%27alaku", "Haka'alaku")],
  },
  {
    canonicalName: "Number City",
    reason: "cognitive-realm",
    note: "A Shadesmar city, outside this Physical-Realm catalog.",
    sources: [coppermind("Number_City", "Number City")],
  },
  {
    canonicalName: "Riino's lighthouse",
    reason: "cognitive-realm",
    note: "A Shadesmar landmark, outside this Physical-Realm catalog.",
    sources: [coppermind("Riino", "Riino")],
  },
  {
    canonicalName: "Stormseat",
    reason: "already-cataloged-alias",
    note: "Already represented by Narak, whose alternate names include Stormseat.",
    sources: [coppermind("Stormseat", "Stormseat")],
  },
] as const;
